// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocolVersion.proto

/*
Package org_apache_geode_internal_protocol_protobuf is a generated protocol buffer package.

It is generated from these files:
	protocolVersion.proto

It has these top-level messages:
	NewConnectionClientVersion
	VersionAcknowledgement
*/
package org_apache_geode_internal_protocol_protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MajorVersions int32

const (
	MajorVersions_INVALID_MAJOR_VERSION MajorVersions = 0
	MajorVersions_CURRENT_MAJOR_VERSION MajorVersions = 1
)

var MajorVersions_name = map[int32]string{
	0: "INVALID_MAJOR_VERSION",
	1: "CURRENT_MAJOR_VERSION",
}
var MajorVersions_value = map[string]int32{
	"INVALID_MAJOR_VERSION": 0,
	"CURRENT_MAJOR_VERSION": 1,
}

func (x MajorVersions) String() string {
	return proto.EnumName(MajorVersions_name, int32(x))
}
func (MajorVersions) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type MinorVersions int32

const (
	MinorVersions_INVALID_MINOR_VERSION MinorVersions = 0
	MinorVersions_CURRENT_MINOR_VERSION MinorVersions = 1
)

var MinorVersions_name = map[int32]string{
	0: "INVALID_MINOR_VERSION",
	1: "CURRENT_MINOR_VERSION",
}
var MinorVersions_value = map[string]int32{
	"INVALID_MINOR_VERSION": 0,
	"CURRENT_MINOR_VERSION": 1,
}

func (x MinorVersions) String() string {
	return proto.EnumName(MinorVersions_name, int32(x))
}
func (MinorVersions) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type NewConnectionClientVersion struct {
	MajorVersion uint32 `protobuf:"fixed32,1,opt,name=majorVersion" json:"majorVersion,omitempty"`
	MinorVersion uint32 `protobuf:"fixed32,2,opt,name=minorVersion" json:"minorVersion,omitempty"`
}

func (m *NewConnectionClientVersion) Reset()                    { *m = NewConnectionClientVersion{} }
func (m *NewConnectionClientVersion) String() string            { return proto.CompactTextString(m) }
func (*NewConnectionClientVersion) ProtoMessage()               {}
func (*NewConnectionClientVersion) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NewConnectionClientVersion) GetMajorVersion() uint32 {
	if m != nil {
		return m.MajorVersion
	}
	return 0
}

func (m *NewConnectionClientVersion) GetMinorVersion() uint32 {
	if m != nil {
		return m.MinorVersion
	}
	return 0
}

type VersionAcknowledgement struct {
	ServerMajorVersion int32 `protobuf:"varint,1,opt,name=serverMajorVersion" json:"serverMajorVersion,omitempty"`
	ServerMinorVersion int32 `protobuf:"varint,2,opt,name=serverMinorVersion" json:"serverMinorVersion,omitempty"`
	VersionAccepted    bool  `protobuf:"varint,3,opt,name=versionAccepted" json:"versionAccepted,omitempty"`
}

func (m *VersionAcknowledgement) Reset()                    { *m = VersionAcknowledgement{} }
func (m *VersionAcknowledgement) String() string            { return proto.CompactTextString(m) }
func (*VersionAcknowledgement) ProtoMessage()               {}
func (*VersionAcknowledgement) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *VersionAcknowledgement) GetServerMajorVersion() int32 {
	if m != nil {
		return m.ServerMajorVersion
	}
	return 0
}

func (m *VersionAcknowledgement) GetServerMinorVersion() int32 {
	if m != nil {
		return m.ServerMinorVersion
	}
	return 0
}

func (m *VersionAcknowledgement) GetVersionAccepted() bool {
	if m != nil {
		return m.VersionAccepted
	}
	return false
}

func init() {
	proto.RegisterType((*NewConnectionClientVersion)(nil), "org.apache.geode.internal.protocol.protobuf.NewConnectionClientVersion")
	proto.RegisterType((*VersionAcknowledgement)(nil), "org.apache.geode.internal.protocol.protobuf.VersionAcknowledgement")
	proto.RegisterEnum("org.apache.geode.internal.protocol.protobuf.MajorVersions", MajorVersions_name, MajorVersions_value)
	proto.RegisterEnum("org.apache.geode.internal.protocol.protobuf.MinorVersions", MinorVersions_name, MinorVersions_value)
}

func init() { proto.RegisterFile("protocolVersion.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x5f, 0x4b, 0xc3, 0x30,
	0x14, 0xc5, 0x8d, 0xe2, 0x1f, 0x82, 0xa2, 0x04, 0x26, 0xd3, 0xa7, 0xb1, 0xa7, 0xa2, 0x90, 0x17,
	0x3f, 0x41, 0xa9, 0x7d, 0xa8, 0xb8, 0x0e, 0xa2, 0xf6, 0x75, 0x74, 0xe9, 0xb5, 0x46, 0xbb, 0x7b,
	0x4b, 0x1a, 0xb7, 0xef, 0xe3, 0x27, 0x15, 0x6b, 0xc7, 0xd2, 0xa2, 0x6f, 0xf7, 0x9e, 0xf3, 0xcb,
	0x39, 0x81, 0xcb, 0x47, 0xb5, 0x25, 0x47, 0x9a, 0xaa, 0x0c, 0x6c, 0x63, 0x08, 0x65, 0xbb, 0x8b,
	0x5b, 0xb2, 0xa5, 0xcc, 0xeb, 0x5c, 0xbf, 0x81, 0x2c, 0x81, 0x0a, 0x90, 0x06, 0x1d, 0x58, 0xcc,
	0x2b, 0xb9, 0x7d, 0xf0, 0x3b, 0x2c, 0x3f, 0x5f, 0xa7, 0x05, 0xbf, 0x4e, 0x61, 0x13, 0x11, 0x22,
	0x68, 0x67, 0x08, 0xa3, 0xca, 0x00, 0xba, 0x2e, 0x50, 0x4c, 0xf9, 0xe9, 0x2a, 0x7f, 0x27, 0xdb,
	0xed, 0x63, 0x36, 0x61, 0xc1, 0xb1, 0xea, 0x69, 0x2d, 0x63, 0x70, 0xc7, 0xec, 0x77, 0x8c, 0xa7,
	0x4d, 0xbf, 0x18, 0xbf, 0xec, 0xe6, 0x50, 0x7f, 0x20, 0x6d, 0x2a, 0x28, 0x4a, 0x58, 0x01, 0x3a,
	0x21, 0xb9, 0x68, 0xc0, 0xae, 0xc1, 0xce, 0x86, 0x45, 0x87, 0xea, 0x0f, 0xc7, 0xe3, 0x87, 0xa5,
	0x3b, 0xde, 0x73, 0x44, 0xc0, 0xcf, 0xd7, 0xdb, 0x66, 0x0d, 0xb5, 0x83, 0x62, 0x7c, 0x30, 0x61,
	0xc1, 0x89, 0x1a, 0xca, 0x37, 0x31, 0x3f, 0xf3, 0x9b, 0x1a, 0x71, 0xc5, 0x47, 0x49, 0x9a, 0x85,
	0x8f, 0xc9, 0xfd, 0x62, 0x16, 0x3e, 0xcc, 0xd5, 0x22, 0x8b, 0xd5, 0x53, 0x32, 0x4f, 0x2f, 0xf6,
	0x7e, 0xac, 0xe8, 0x45, 0xa9, 0x38, 0x7d, 0x1e, 0x58, 0xac, 0x8d, 0xf1, 0x3e, 0xd0, 0x8f, 0x49,
	0xd2, 0x7f, 0x63, 0x7a, 0x16, 0x5b, 0x1e, 0xb5, 0x27, 0xba, 0xfb, 0x0e, 0x00, 0x00, 0xff, 0xff,
	0x7d, 0xc9, 0xa2, 0x3b, 0xe5, 0x01, 0x00, 0x00,
}
