// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v1/basicTypes.proto

/*
Package org_apache_geode_internal_protocol_protobuf_v1 is a generated protocol buffer package.

It is generated from these files:
	v1/basicTypes.proto
	v1/clientProtocol.proto
	v1/connection_API.proto
	v1/locator_API.proto
	v1/region_API.proto
	v1/function_API.proto

It has these top-level messages:
	Entry
	EncodedValueList
	Table
	EncodedValue
	Server
	Error
	KeyedError
	Message
	ErrorResponse
	HandshakeRequest
	HandshakeResponse
	DisconnectClientRequest
	DisconnectClientResponse
	GetServerRequest
	GetServerResponse
	PutRequest
	PutResponse
	PutIfAbsentRequest
	PutIfAbsentResponse
	GetRequest
	GetResponse
	PutAllRequest
	PutAllResponse
	GetAllRequest
	GetAllResponse
	RemoveRequest
	RemoveResponse
	GetRegionNamesRequest
	GetRegionNamesResponse
	GetSizeRequest
	GetSizeResponse
	OQLQueryRequest
	OQLQueryResponse
	KeySetRequest
	KeySetResponse
	ClearRequest
	ClearResponse
	ExecuteFunctionOnRegionRequest
	ExecuteFunctionOnRegionResponse
	ExecuteFunctionOnMemberRequest
	ExecuteFunctionOnMemberResponse
	ExecuteFunctionOnGroupRequest
	ExecuteFunctionOnGroupResponse
*/
package org_apache_geode_internal_protocol_protobuf_v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/struct"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ErrorCode int32

const (
	ErrorCode_INVALID_ERROR_CODE           ErrorCode = 0
	ErrorCode_AUTHENTICATION_REQUIRED      ErrorCode = 10
	ErrorCode_AUTHENTICATION_FAILED        ErrorCode = 11
	ErrorCode_ALREADY_AUTHENTICATED        ErrorCode = 12
	ErrorCode_AUTHENTICATION_NOT_SUPPORTED ErrorCode = 13
	ErrorCode_AUTHORIZATION_FAILED         ErrorCode = 20
	ErrorCode_INVALID_REQUEST              ErrorCode = 50
	ErrorCode_UNSUPPORTED_OPERATION        ErrorCode = 60
	ErrorCode_SERVER_ERROR                 ErrorCode = 100
	ErrorCode_NO_AVAILABLE_SERVER          ErrorCode = 101
)

var ErrorCode_name = map[int32]string{
	0:   "INVALID_ERROR_CODE",
	10:  "AUTHENTICATION_REQUIRED",
	11:  "AUTHENTICATION_FAILED",
	12:  "ALREADY_AUTHENTICATED",
	13:  "AUTHENTICATION_NOT_SUPPORTED",
	20:  "AUTHORIZATION_FAILED",
	50:  "INVALID_REQUEST",
	60:  "UNSUPPORTED_OPERATION",
	100: "SERVER_ERROR",
	101: "NO_AVAILABLE_SERVER",
}
var ErrorCode_value = map[string]int32{
	"INVALID_ERROR_CODE":           0,
	"AUTHENTICATION_REQUIRED":      10,
	"AUTHENTICATION_FAILED":        11,
	"ALREADY_AUTHENTICATED":        12,
	"AUTHENTICATION_NOT_SUPPORTED": 13,
	"AUTHORIZATION_FAILED":         20,
	"INVALID_REQUEST":              50,
	"UNSUPPORTED_OPERATION":        60,
	"SERVER_ERROR":                 100,
	"NO_AVAILABLE_SERVER":          101,
}

func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}
func (ErrorCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Entry struct {
	Key   *EncodedValue `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value *EncodedValue `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *Entry) Reset()                    { *m = Entry{} }
func (m *Entry) String() string            { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()               {}
func (*Entry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Entry) GetKey() *EncodedValue {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Entry) GetValue() *EncodedValue {
	if m != nil {
		return m.Value
	}
	return nil
}

type EncodedValueList struct {
	Element []*EncodedValue `protobuf:"bytes,1,rep,name=element" json:"element,omitempty"`
}

func (m *EncodedValueList) Reset()                    { *m = EncodedValueList{} }
func (m *EncodedValueList) String() string            { return proto.CompactTextString(m) }
func (*EncodedValueList) ProtoMessage()               {}
func (*EncodedValueList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *EncodedValueList) GetElement() []*EncodedValue {
	if m != nil {
		return m.Element
	}
	return nil
}

// Represents a table, such as the results of
// an OQL query. The field names and all rows
// should have the same number of elements.
type Table struct {
	FieldName []string            `protobuf:"bytes,1,rep,name=fieldName" json:"fieldName,omitempty"`
	Row       []*EncodedValueList `protobuf:"bytes,2,rep,name=row" json:"row,omitempty"`
}

func (m *Table) Reset()                    { *m = Table{} }
func (m *Table) String() string            { return proto.CompactTextString(m) }
func (*Table) ProtoMessage()               {}
func (*Table) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Table) GetFieldName() []string {
	if m != nil {
		return m.FieldName
	}
	return nil
}

func (m *Table) GetRow() []*EncodedValueList {
	if m != nil {
		return m.Row
	}
	return nil
}

type EncodedValue struct {
	// Types that are valid to be assigned to Value:
	//	*EncodedValue_IntResult
	//	*EncodedValue_LongResult
	//	*EncodedValue_ShortResult
	//	*EncodedValue_ByteResult
	//	*EncodedValue_BooleanResult
	//	*EncodedValue_DoubleResult
	//	*EncodedValue_FloatResult
	//	*EncodedValue_BinaryResult
	//	*EncodedValue_StringResult
	//	*EncodedValue_JsonObjectResult
	//	*EncodedValue_NullResult
	//	*EncodedValue_CustomObjectResult
	Value isEncodedValue_Value `protobuf_oneof:"value"`
}

func (m *EncodedValue) Reset()                    { *m = EncodedValue{} }
func (m *EncodedValue) String() string            { return proto.CompactTextString(m) }
func (*EncodedValue) ProtoMessage()               {}
func (*EncodedValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type isEncodedValue_Value interface {
	isEncodedValue_Value()
}

type EncodedValue_IntResult struct {
	IntResult int32 `protobuf:"varint,1,opt,name=intResult,oneof"`
}
type EncodedValue_LongResult struct {
	LongResult int64 `protobuf:"varint,2,opt,name=longResult,oneof"`
}
type EncodedValue_ShortResult struct {
	ShortResult int32 `protobuf:"varint,3,opt,name=shortResult,oneof"`
}
type EncodedValue_ByteResult struct {
	ByteResult int32 `protobuf:"varint,4,opt,name=byteResult,oneof"`
}
type EncodedValue_BooleanResult struct {
	BooleanResult bool `protobuf:"varint,5,opt,name=booleanResult,oneof"`
}
type EncodedValue_DoubleResult struct {
	DoubleResult float64 `protobuf:"fixed64,6,opt,name=doubleResult,oneof"`
}
type EncodedValue_FloatResult struct {
	FloatResult float32 `protobuf:"fixed32,7,opt,name=floatResult,oneof"`
}
type EncodedValue_BinaryResult struct {
	BinaryResult []byte `protobuf:"bytes,8,opt,name=binaryResult,proto3,oneof"`
}
type EncodedValue_StringResult struct {
	StringResult string `protobuf:"bytes,9,opt,name=stringResult,oneof"`
}
type EncodedValue_JsonObjectResult struct {
	JsonObjectResult string `protobuf:"bytes,10,opt,name=jsonObjectResult,oneof"`
}
type EncodedValue_NullResult struct {
	NullResult google_protobuf.NullValue `protobuf:"varint,11,opt,name=nullResult,enum=google.protobuf.NullValue,oneof"`
}
type EncodedValue_CustomObjectResult struct {
	CustomObjectResult []byte `protobuf:"bytes,12,opt,name=customObjectResult,proto3,oneof"`
}

func (*EncodedValue_IntResult) isEncodedValue_Value()          {}
func (*EncodedValue_LongResult) isEncodedValue_Value()         {}
func (*EncodedValue_ShortResult) isEncodedValue_Value()        {}
func (*EncodedValue_ByteResult) isEncodedValue_Value()         {}
func (*EncodedValue_BooleanResult) isEncodedValue_Value()      {}
func (*EncodedValue_DoubleResult) isEncodedValue_Value()       {}
func (*EncodedValue_FloatResult) isEncodedValue_Value()        {}
func (*EncodedValue_BinaryResult) isEncodedValue_Value()       {}
func (*EncodedValue_StringResult) isEncodedValue_Value()       {}
func (*EncodedValue_JsonObjectResult) isEncodedValue_Value()   {}
func (*EncodedValue_NullResult) isEncodedValue_Value()         {}
func (*EncodedValue_CustomObjectResult) isEncodedValue_Value() {}

func (m *EncodedValue) GetValue() isEncodedValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *EncodedValue) GetIntResult() int32 {
	if x, ok := m.GetValue().(*EncodedValue_IntResult); ok {
		return x.IntResult
	}
	return 0
}

func (m *EncodedValue) GetLongResult() int64 {
	if x, ok := m.GetValue().(*EncodedValue_LongResult); ok {
		return x.LongResult
	}
	return 0
}

func (m *EncodedValue) GetShortResult() int32 {
	if x, ok := m.GetValue().(*EncodedValue_ShortResult); ok {
		return x.ShortResult
	}
	return 0
}

func (m *EncodedValue) GetByteResult() int32 {
	if x, ok := m.GetValue().(*EncodedValue_ByteResult); ok {
		return x.ByteResult
	}
	return 0
}

func (m *EncodedValue) GetBooleanResult() bool {
	if x, ok := m.GetValue().(*EncodedValue_BooleanResult); ok {
		return x.BooleanResult
	}
	return false
}

func (m *EncodedValue) GetDoubleResult() float64 {
	if x, ok := m.GetValue().(*EncodedValue_DoubleResult); ok {
		return x.DoubleResult
	}
	return 0
}

func (m *EncodedValue) GetFloatResult() float32 {
	if x, ok := m.GetValue().(*EncodedValue_FloatResult); ok {
		return x.FloatResult
	}
	return 0
}

func (m *EncodedValue) GetBinaryResult() []byte {
	if x, ok := m.GetValue().(*EncodedValue_BinaryResult); ok {
		return x.BinaryResult
	}
	return nil
}

func (m *EncodedValue) GetStringResult() string {
	if x, ok := m.GetValue().(*EncodedValue_StringResult); ok {
		return x.StringResult
	}
	return ""
}

func (m *EncodedValue) GetJsonObjectResult() string {
	if x, ok := m.GetValue().(*EncodedValue_JsonObjectResult); ok {
		return x.JsonObjectResult
	}
	return ""
}

func (m *EncodedValue) GetNullResult() google_protobuf.NullValue {
	if x, ok := m.GetValue().(*EncodedValue_NullResult); ok {
		return x.NullResult
	}
	return google_protobuf.NullValue_NULL_VALUE
}

func (m *EncodedValue) GetCustomObjectResult() []byte {
	if x, ok := m.GetValue().(*EncodedValue_CustomObjectResult); ok {
		return x.CustomObjectResult
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*EncodedValue) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _EncodedValue_OneofMarshaler, _EncodedValue_OneofUnmarshaler, _EncodedValue_OneofSizer, []interface{}{
		(*EncodedValue_IntResult)(nil),
		(*EncodedValue_LongResult)(nil),
		(*EncodedValue_ShortResult)(nil),
		(*EncodedValue_ByteResult)(nil),
		(*EncodedValue_BooleanResult)(nil),
		(*EncodedValue_DoubleResult)(nil),
		(*EncodedValue_FloatResult)(nil),
		(*EncodedValue_BinaryResult)(nil),
		(*EncodedValue_StringResult)(nil),
		(*EncodedValue_JsonObjectResult)(nil),
		(*EncodedValue_NullResult)(nil),
		(*EncodedValue_CustomObjectResult)(nil),
	}
}

func _EncodedValue_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*EncodedValue)
	// value
	switch x := m.Value.(type) {
	case *EncodedValue_IntResult:
		b.EncodeVarint(1<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.IntResult))
	case *EncodedValue_LongResult:
		b.EncodeVarint(2<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.LongResult))
	case *EncodedValue_ShortResult:
		b.EncodeVarint(3<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.ShortResult))
	case *EncodedValue_ByteResult:
		b.EncodeVarint(4<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.ByteResult))
	case *EncodedValue_BooleanResult:
		t := uint64(0)
		if x.BooleanResult {
			t = 1
		}
		b.EncodeVarint(5<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case *EncodedValue_DoubleResult:
		b.EncodeVarint(6<<3 | proto.WireFixed64)
		b.EncodeFixed64(math.Float64bits(x.DoubleResult))
	case *EncodedValue_FloatResult:
		b.EncodeVarint(7<<3 | proto.WireFixed32)
		b.EncodeFixed32(uint64(math.Float32bits(x.FloatResult)))
	case *EncodedValue_BinaryResult:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.BinaryResult)
	case *EncodedValue_StringResult:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.StringResult)
	case *EncodedValue_JsonObjectResult:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.JsonObjectResult)
	case *EncodedValue_NullResult:
		b.EncodeVarint(11<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.NullResult))
	case *EncodedValue_CustomObjectResult:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.CustomObjectResult)
	case nil:
	default:
		return fmt.Errorf("EncodedValue.Value has unexpected type %T", x)
	}
	return nil
}

func _EncodedValue_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*EncodedValue)
	switch tag {
	case 1: // value.intResult
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &EncodedValue_IntResult{int32(x)}
		return true, err
	case 2: // value.longResult
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &EncodedValue_LongResult{int64(x)}
		return true, err
	case 3: // value.shortResult
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &EncodedValue_ShortResult{int32(x)}
		return true, err
	case 4: // value.byteResult
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &EncodedValue_ByteResult{int32(x)}
		return true, err
	case 5: // value.booleanResult
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &EncodedValue_BooleanResult{x != 0}
		return true, err
	case 6: // value.doubleResult
		if wire != proto.WireFixed64 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed64()
		m.Value = &EncodedValue_DoubleResult{math.Float64frombits(x)}
		return true, err
	case 7: // value.floatResult
		if wire != proto.WireFixed32 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed32()
		m.Value = &EncodedValue_FloatResult{math.Float32frombits(uint32(x))}
		return true, err
	case 8: // value.binaryResult
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.Value = &EncodedValue_BinaryResult{x}
		return true, err
	case 9: // value.stringResult
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Value = &EncodedValue_StringResult{x}
		return true, err
	case 10: // value.jsonObjectResult
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Value = &EncodedValue_JsonObjectResult{x}
		return true, err
	case 11: // value.nullResult
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &EncodedValue_NullResult{google_protobuf.NullValue(x)}
		return true, err
	case 12: // value.customObjectResult
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.Value = &EncodedValue_CustomObjectResult{x}
		return true, err
	default:
		return false, nil
	}
}

func _EncodedValue_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*EncodedValue)
	// value
	switch x := m.Value.(type) {
	case *EncodedValue_IntResult:
		n += proto.SizeVarint(1<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.IntResult))
	case *EncodedValue_LongResult:
		n += proto.SizeVarint(2<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.LongResult))
	case *EncodedValue_ShortResult:
		n += proto.SizeVarint(3<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.ShortResult))
	case *EncodedValue_ByteResult:
		n += proto.SizeVarint(4<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.ByteResult))
	case *EncodedValue_BooleanResult:
		n += proto.SizeVarint(5<<3 | proto.WireVarint)
		n += 1
	case *EncodedValue_DoubleResult:
		n += proto.SizeVarint(6<<3 | proto.WireFixed64)
		n += 8
	case *EncodedValue_FloatResult:
		n += proto.SizeVarint(7<<3 | proto.WireFixed32)
		n += 4
	case *EncodedValue_BinaryResult:
		n += proto.SizeVarint(8<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.BinaryResult)))
		n += len(x.BinaryResult)
	case *EncodedValue_StringResult:
		n += proto.SizeVarint(9<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.StringResult)))
		n += len(x.StringResult)
	case *EncodedValue_JsonObjectResult:
		n += proto.SizeVarint(10<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.JsonObjectResult)))
		n += len(x.JsonObjectResult)
	case *EncodedValue_NullResult:
		n += proto.SizeVarint(11<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.NullResult))
	case *EncodedValue_CustomObjectResult:
		n += proto.SizeVarint(12<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.CustomObjectResult)))
		n += len(x.CustomObjectResult)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Server struct {
	Hostname string `protobuf:"bytes,1,opt,name=hostname" json:"hostname,omitempty"`
	Port     int32  `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
}

func (m *Server) Reset()                    { *m = Server{} }
func (m *Server) String() string            { return proto.CompactTextString(m) }
func (*Server) ProtoMessage()               {}
func (*Server) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Server) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Server) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type Error struct {
	ErrorCode ErrorCode `protobuf:"varint,1,opt,name=errorCode,enum=org.apache.geode.internal.protocol.protobuf.v1.ErrorCode" json:"errorCode,omitempty"`
	Message   string    `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Error) GetErrorCode() ErrorCode {
	if m != nil {
		return m.ErrorCode
	}
	return ErrorCode_INVALID_ERROR_CODE
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type KeyedError struct {
	Key   *EncodedValue `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Error *Error        `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *KeyedError) Reset()                    { *m = KeyedError{} }
func (m *KeyedError) String() string            { return proto.CompactTextString(m) }
func (*KeyedError) ProtoMessage()               {}
func (*KeyedError) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *KeyedError) GetKey() *EncodedValue {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *KeyedError) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*Entry)(nil), "org.apache.geode.internal.protocol.protobuf.v1.Entry")
	proto.RegisterType((*EncodedValueList)(nil), "org.apache.geode.internal.protocol.protobuf.v1.EncodedValueList")
	proto.RegisterType((*Table)(nil), "org.apache.geode.internal.protocol.protobuf.v1.Table")
	proto.RegisterType((*EncodedValue)(nil), "org.apache.geode.internal.protocol.protobuf.v1.EncodedValue")
	proto.RegisterType((*Server)(nil), "org.apache.geode.internal.protocol.protobuf.v1.Server")
	proto.RegisterType((*Error)(nil), "org.apache.geode.internal.protocol.protobuf.v1.Error")
	proto.RegisterType((*KeyedError)(nil), "org.apache.geode.internal.protocol.protobuf.v1.KeyedError")
	proto.RegisterEnum("org.apache.geode.internal.protocol.protobuf.v1.ErrorCode", ErrorCode_name, ErrorCode_value)
}

func init() { proto.RegisterFile("v1/basicTypes.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 721 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x5d, 0x6f, 0xe3, 0x44,
	0x14, 0x8d, 0x93, 0xba, 0xa9, 0x6f, 0xd2, 0x62, 0x4d, 0x0b, 0x0d, 0xa5, 0x42, 0x96, 0x85, 0x90,
	0x85, 0x90, 0x4b, 0x83, 0x90, 0x40, 0xea, 0x03, 0x6e, 0x33, 0x28, 0x56, 0x23, 0xbb, 0x4c, 0x3e,
	0x10, 0xbc, 0x58, 0x76, 0x3c, 0x4d, 0x53, 0x1c, 0x4f, 0xe4, 0x8f, 0xa0, 0xf0, 0x1f, 0xf6, 0x87,
	0xac, 0xf6, 0x27, 0xee, 0xcb, 0x6a, 0xfc, 0x91, 0x38, 0xdd, 0x7d, 0xe9, 0xb6, 0x6f, 0x33, 0xe7,
	0x9e, 0x39, 0xe7, 0xcc, 0xbd, 0x1e, 0xc3, 0xf1, 0xea, 0xf2, 0xc2, 0x73, 0xe3, 0xf9, 0x74, 0xb4,
	0x5e, 0xd2, 0x58, 0x5f, 0x46, 0x2c, 0x61, 0x48, 0x67, 0xd1, 0x4c, 0x77, 0x97, 0xee, 0xf4, 0x81,
	0xea, 0x33, 0xca, 0x7c, 0xaa, 0xcf, 0xc3, 0x84, 0x46, 0xa1, 0x1b, 0xe4, 0x84, 0x29, 0x2b, 0x16,
	0x5e, 0x7a, 0xaf, 0xaf, 0x2e, 0xcf, 0xce, 0x67, 0x8c, 0xcd, 0x02, 0x7a, 0x51, 0x62, 0x17, 0x71,
	0x12, 0xa5, 0xd3, 0x24, 0xe7, 0xa8, 0xef, 0x04, 0x10, 0x71, 0x98, 0x44, 0x6b, 0x64, 0x41, 0xe3,
	0x5f, 0xba, 0xee, 0x08, 0x8a, 0xa0, 0xb5, 0xba, 0x57, 0xcf, 0x74, 0xd1, 0x71, 0x38, 0x65, 0x3e,
	0xf5, 0x27, 0x6e, 0x90, 0x52, 0xc2, 0x85, 0x10, 0x01, 0x71, 0xc5, 0x77, 0x9d, 0xfa, 0x2b, 0x28,
	0xe6, 0x52, 0xea, 0x23, 0xc8, 0x55, 0x78, 0x30, 0x8f, 0x13, 0x34, 0x81, 0x26, 0x0d, 0xe8, 0x82,
	0x86, 0x49, 0x47, 0x50, 0x1a, 0x2f, 0x76, 0x2a, 0xc5, 0xd4, 0x35, 0x88, 0x23, 0xd7, 0x0b, 0x28,
	0x3a, 0x07, 0xe9, 0x7e, 0x4e, 0x03, 0xdf, 0x72, 0x17, 0x34, 0xb3, 0x90, 0xc8, 0x16, 0x40, 0x04,
	0x1a, 0x11, 0xfb, 0xaf, 0x53, 0xcf, 0xac, 0x7f, 0x7f, 0x89, 0x35, 0xbf, 0x0d, 0xe1, 0x62, 0xea,
	0xfb, 0x06, 0xb4, 0xab, 0x15, 0xf4, 0x2d, 0x48, 0xf3, 0x30, 0x21, 0x34, 0x4e, 0x83, 0x24, 0x9b,
	0x90, 0xd8, 0xaf, 0x91, 0x2d, 0x84, 0x14, 0x80, 0x80, 0x85, 0xb3, 0x82, 0xc0, 0x1b, 0xde, 0xe8,
	0xd7, 0x48, 0x05, 0x43, 0x2a, 0xb4, 0xe2, 0x07, 0x16, 0x95, 0x1a, 0x8d, 0x42, 0xa3, 0x0a, 0x72,
	0x15, 0x6f, 0x9d, 0xd0, 0x82, 0xb2, 0x57, 0x50, 0x2a, 0x18, 0xfa, 0x1e, 0x0e, 0x3d, 0xc6, 0x02,
	0xea, 0x86, 0x05, 0x49, 0x54, 0x04, 0xed, 0xa0, 0x5f, 0x23, 0xbb, 0x30, 0xfa, 0x0e, 0xda, 0x3e,
	0x4b, 0xbd, 0xa0, 0xd4, 0xda, 0x57, 0x04, 0x4d, 0xe8, 0xd7, 0xc8, 0x0e, 0xca, 0x33, 0xdd, 0x07,
	0xcc, 0x2d, 0x33, 0x35, 0x15, 0x41, 0xab, 0xf3, 0x4c, 0x15, 0x90, 0x2b, 0x79, 0xf3, 0xd0, 0x8d,
	0xd6, 0x05, 0xe9, 0x40, 0x11, 0xb4, 0x36, 0x57, 0xaa, 0xa2, 0x9c, 0x15, 0x27, 0xd1, 0x7c, 0xd3,
	0x01, 0x49, 0x11, 0x34, 0x89, 0xb3, 0xaa, 0x28, 0xfa, 0x11, 0xe4, 0xc7, 0x98, 0x85, 0xb6, 0xf7,
	0x48, 0xa7, 0xa5, 0x29, 0x14, 0xcc, 0x8f, 0x2a, 0xe8, 0x0a, 0x20, 0x4c, 0x83, 0xa0, 0xe0, 0xb5,
	0x14, 0x41, 0x3b, 0xea, 0x9e, 0xe9, 0xf9, 0x63, 0xda, 0xce, 0xd0, 0x4a, 0x83, 0x20, 0x9b, 0x11,
	0xef, 0xd4, 0x96, 0x8f, 0x7e, 0x02, 0x34, 0x4d, 0xe3, 0x84, 0x2d, 0x76, 0xdc, 0xda, 0x45, 0xfa,
	0x4f, 0xd4, 0xae, 0x9b, 0xc5, 0x7b, 0x51, 0x7f, 0x85, 0xfd, 0x21, 0x8d, 0x56, 0x34, 0x42, 0x67,
	0x70, 0xf0, 0xc0, 0xe2, 0x24, 0xcc, 0x3f, 0x3c, 0x41, 0x93, 0xc8, 0x66, 0x8f, 0x10, 0xec, 0x2d,
	0x59, 0x94, 0x0f, 0x5b, 0x24, 0xd9, 0x5a, 0xfd, 0x1f, 0x44, 0x1c, 0x45, 0x2c, 0x42, 0x7f, 0x81,
	0x44, 0xf9, 0xe2, 0x86, 0xf9, 0xf9, 0xc9, 0xa3, 0xee, 0x6f, 0xcf, 0xfe, 0x34, 0x4b, 0x01, 0xb2,
	0xd5, 0x42, 0x1d, 0x68, 0x2e, 0x68, 0x1c, 0xbb, 0xb3, 0xfc, 0x59, 0x4b, 0xa4, 0xdc, 0xaa, 0x6f,
	0x05, 0x80, 0x5b, 0xba, 0xa6, 0x7e, 0x9e, 0xe0, 0xb5, 0xff, 0x26, 0xb7, 0x20, 0x66, 0x29, 0x8a,
	0xbf, 0xc9, 0x2f, 0x9f, 0x75, 0x1b, 0x92, 0x6b, 0xfc, 0xf0, 0xa6, 0x0e, 0xd2, 0xe6, 0x7a, 0xe8,
	0x2b, 0x40, 0xa6, 0x35, 0x31, 0x06, 0x66, 0xcf, 0xc1, 0x84, 0xd8, 0xc4, 0xb9, 0xb1, 0x7b, 0x58,
	0xae, 0xa1, 0x6f, 0xe0, 0xd4, 0x18, 0x8f, 0xfa, 0xd8, 0x1a, 0x99, 0x37, 0xc6, 0xc8, 0xb4, 0x2d,
	0x87, 0xe0, 0x3f, 0xc7, 0x26, 0xc1, 0x3d, 0x19, 0xd0, 0xd7, 0xf0, 0xe5, 0x93, 0xe2, 0x1f, 0x86,
	0x39, 0xc0, 0x3d, 0xb9, 0x95, 0x95, 0x06, 0x04, 0x1b, 0xbd, 0xbf, 0x9d, 0x0a, 0x05, 0xf7, 0xe4,
	0x36, 0x52, 0xe0, 0xfc, 0xc9, 0x29, 0xcb, 0x1e, 0x39, 0xc3, 0xf1, 0xdd, 0x9d, 0x4d, 0x38, 0xe3,
	0x10, 0x75, 0xe0, 0x84, 0x33, 0x6c, 0x62, 0xfe, 0xb3, 0x23, 0x7b, 0x82, 0x8e, 0xe1, 0x8b, 0x32,
	0x26, 0xcf, 0x81, 0x87, 0x23, 0xb9, 0xcb, 0xbd, 0xc6, 0xd6, 0xe6, 0xbc, 0x63, 0xdf, 0x61, 0x92,
	0x1d, 0x93, 0xaf, 0x90, 0x0c, 0xed, 0x21, 0x26, 0x13, 0x4c, 0xf2, 0x5b, 0xc9, 0x3e, 0x3a, 0x85,
	0x63, 0xcb, 0x76, 0x8c, 0x89, 0x61, 0x0e, 0x8c, 0xeb, 0x01, 0x76, 0xf2, 0xb2, 0x4c, 0xbd, 0xfd,
	0xac, 0x53, 0x3f, 0x7f, 0x08, 0x00, 0x00, 0xff, 0xff, 0xde, 0x51, 0x01, 0xf7, 0x70, 0x06, 0x00,
	0x00,
}
