// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v1/clientProtocol.proto

package org_apache_geode_internal_protocol_protobuf_v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Message struct {
	// Types that are valid to be assigned to MessageType:
	//	*Message_ErrorResponse
	//	*Message_PutRequest
	//	*Message_PutResponse
	//	*Message_GetRequest
	//	*Message_GetResponse
	//	*Message_PutAllRequest
	//	*Message_PutAllResponse
	//	*Message_GetAllRequest
	//	*Message_GetAllResponse
	//	*Message_RemoveRequest
	//	*Message_RemoveResponse
	//	*Message_GetServerRequest
	//	*Message_GetServerResponse
	//	*Message_GetRegionNamesRequest
	//	*Message_GetRegionNamesResponse
	//	*Message_GetRegionRequest
	//	*Message_GetRegionResponse
	//	*Message_ExecuteFunctionOnRegionRequest
	//	*Message_ExecuteFunctionOnRegionResponse
	//	*Message_AuthenticationRequest
	//	*Message_AuthenticationResponse
	MessageType isMessage_MessageType `protobuf_oneof:"messageType"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type isMessage_MessageType interface {
	isMessage_MessageType()
}

type Message_ErrorResponse struct {
	ErrorResponse *ErrorResponse `protobuf:"bytes,1,opt,name=errorResponse,oneof"`
}
type Message_PutRequest struct {
	PutRequest *PutRequest `protobuf:"bytes,2,opt,name=putRequest,oneof"`
}
type Message_PutResponse struct {
	PutResponse *PutResponse `protobuf:"bytes,3,opt,name=putResponse,oneof"`
}
type Message_GetRequest struct {
	GetRequest *GetRequest `protobuf:"bytes,4,opt,name=getRequest,oneof"`
}
type Message_GetResponse struct {
	GetResponse *GetResponse `protobuf:"bytes,5,opt,name=getResponse,oneof"`
}
type Message_PutAllRequest struct {
	PutAllRequest *PutAllRequest `protobuf:"bytes,6,opt,name=putAllRequest,oneof"`
}
type Message_PutAllResponse struct {
	PutAllResponse *PutAllResponse `protobuf:"bytes,7,opt,name=putAllResponse,oneof"`
}
type Message_GetAllRequest struct {
	GetAllRequest *GetAllRequest `protobuf:"bytes,8,opt,name=getAllRequest,oneof"`
}
type Message_GetAllResponse struct {
	GetAllResponse *GetAllResponse `protobuf:"bytes,9,opt,name=getAllResponse,oneof"`
}
type Message_RemoveRequest struct {
	RemoveRequest *RemoveRequest `protobuf:"bytes,10,opt,name=removeRequest,oneof"`
}
type Message_RemoveResponse struct {
	RemoveResponse *RemoveResponse `protobuf:"bytes,11,opt,name=removeResponse,oneof"`
}
type Message_GetServerRequest struct {
	GetServerRequest *GetServerRequest `protobuf:"bytes,12,opt,name=getServerRequest,oneof"`
}
type Message_GetServerResponse struct {
	GetServerResponse *GetServerResponse `protobuf:"bytes,13,opt,name=getServerResponse,oneof"`
}
type Message_GetRegionNamesRequest struct {
	GetRegionNamesRequest *GetRegionNamesRequest `protobuf:"bytes,14,opt,name=getRegionNamesRequest,oneof"`
}
type Message_GetRegionNamesResponse struct {
	GetRegionNamesResponse *GetRegionNamesResponse `protobuf:"bytes,15,opt,name=getRegionNamesResponse,oneof"`
}
type Message_GetRegionRequest struct {
	GetRegionRequest *GetRegionRequest `protobuf:"bytes,16,opt,name=getRegionRequest,oneof"`
}
type Message_GetRegionResponse struct {
	GetRegionResponse *GetRegionResponse `protobuf:"bytes,17,opt,name=getRegionResponse,oneof"`
}
type Message_ExecuteFunctionOnRegionRequest struct {
	ExecuteFunctionOnRegionRequest *ExecuteFunctionOnRegionRequest `protobuf:"bytes,18,opt,name=executeFunctionOnRegionRequest,oneof"`
}
type Message_ExecuteFunctionOnRegionResponse struct {
	ExecuteFunctionOnRegionResponse *ExecuteFunctionOnRegionResponse `protobuf:"bytes,19,opt,name=executeFunctionOnRegionResponse,oneof"`
}
type Message_AuthenticationRequest struct {
	AuthenticationRequest *AuthenticationRequest `protobuf:"bytes,20,opt,name=authenticationRequest,oneof"`
}
type Message_AuthenticationResponse struct {
	AuthenticationResponse *AuthenticationResponse `protobuf:"bytes,21,opt,name=authenticationResponse,oneof"`
}

func (*Message_ErrorResponse) isMessage_MessageType()                   {}
func (*Message_PutRequest) isMessage_MessageType()                      {}
func (*Message_PutResponse) isMessage_MessageType()                     {}
func (*Message_GetRequest) isMessage_MessageType()                      {}
func (*Message_GetResponse) isMessage_MessageType()                     {}
func (*Message_PutAllRequest) isMessage_MessageType()                   {}
func (*Message_PutAllResponse) isMessage_MessageType()                  {}
func (*Message_GetAllRequest) isMessage_MessageType()                   {}
func (*Message_GetAllResponse) isMessage_MessageType()                  {}
func (*Message_RemoveRequest) isMessage_MessageType()                   {}
func (*Message_RemoveResponse) isMessage_MessageType()                  {}
func (*Message_GetServerRequest) isMessage_MessageType()                {}
func (*Message_GetServerResponse) isMessage_MessageType()               {}
func (*Message_GetRegionNamesRequest) isMessage_MessageType()           {}
func (*Message_GetRegionNamesResponse) isMessage_MessageType()          {}
func (*Message_GetRegionRequest) isMessage_MessageType()                {}
func (*Message_GetRegionResponse) isMessage_MessageType()               {}
func (*Message_ExecuteFunctionOnRegionRequest) isMessage_MessageType()  {}
func (*Message_ExecuteFunctionOnRegionResponse) isMessage_MessageType() {}
func (*Message_AuthenticationRequest) isMessage_MessageType()           {}
func (*Message_AuthenticationResponse) isMessage_MessageType()          {}

func (m *Message) GetMessageType() isMessage_MessageType {
	if m != nil {
		return m.MessageType
	}
	return nil
}

func (m *Message) GetErrorResponse() *ErrorResponse {
	if x, ok := m.GetMessageType().(*Message_ErrorResponse); ok {
		return x.ErrorResponse
	}
	return nil
}

func (m *Message) GetPutRequest() *PutRequest {
	if x, ok := m.GetMessageType().(*Message_PutRequest); ok {
		return x.PutRequest
	}
	return nil
}

func (m *Message) GetPutResponse() *PutResponse {
	if x, ok := m.GetMessageType().(*Message_PutResponse); ok {
		return x.PutResponse
	}
	return nil
}

func (m *Message) GetGetRequest() *GetRequest {
	if x, ok := m.GetMessageType().(*Message_GetRequest); ok {
		return x.GetRequest
	}
	return nil
}

func (m *Message) GetGetResponse() *GetResponse {
	if x, ok := m.GetMessageType().(*Message_GetResponse); ok {
		return x.GetResponse
	}
	return nil
}

func (m *Message) GetPutAllRequest() *PutAllRequest {
	if x, ok := m.GetMessageType().(*Message_PutAllRequest); ok {
		return x.PutAllRequest
	}
	return nil
}

func (m *Message) GetPutAllResponse() *PutAllResponse {
	if x, ok := m.GetMessageType().(*Message_PutAllResponse); ok {
		return x.PutAllResponse
	}
	return nil
}

func (m *Message) GetGetAllRequest() *GetAllRequest {
	if x, ok := m.GetMessageType().(*Message_GetAllRequest); ok {
		return x.GetAllRequest
	}
	return nil
}

func (m *Message) GetGetAllResponse() *GetAllResponse {
	if x, ok := m.GetMessageType().(*Message_GetAllResponse); ok {
		return x.GetAllResponse
	}
	return nil
}

func (m *Message) GetRemoveRequest() *RemoveRequest {
	if x, ok := m.GetMessageType().(*Message_RemoveRequest); ok {
		return x.RemoveRequest
	}
	return nil
}

func (m *Message) GetRemoveResponse() *RemoveResponse {
	if x, ok := m.GetMessageType().(*Message_RemoveResponse); ok {
		return x.RemoveResponse
	}
	return nil
}

func (m *Message) GetGetServerRequest() *GetServerRequest {
	if x, ok := m.GetMessageType().(*Message_GetServerRequest); ok {
		return x.GetServerRequest
	}
	return nil
}

func (m *Message) GetGetServerResponse() *GetServerResponse {
	if x, ok := m.GetMessageType().(*Message_GetServerResponse); ok {
		return x.GetServerResponse
	}
	return nil
}

func (m *Message) GetGetRegionNamesRequest() *GetRegionNamesRequest {
	if x, ok := m.GetMessageType().(*Message_GetRegionNamesRequest); ok {
		return x.GetRegionNamesRequest
	}
	return nil
}

func (m *Message) GetGetRegionNamesResponse() *GetRegionNamesResponse {
	if x, ok := m.GetMessageType().(*Message_GetRegionNamesResponse); ok {
		return x.GetRegionNamesResponse
	}
	return nil
}

func (m *Message) GetGetRegionRequest() *GetRegionRequest {
	if x, ok := m.GetMessageType().(*Message_GetRegionRequest); ok {
		return x.GetRegionRequest
	}
	return nil
}

func (m *Message) GetGetRegionResponse() *GetRegionResponse {
	if x, ok := m.GetMessageType().(*Message_GetRegionResponse); ok {
		return x.GetRegionResponse
	}
	return nil
}

func (m *Message) GetExecuteFunctionOnRegionRequest() *ExecuteFunctionOnRegionRequest {
	if x, ok := m.GetMessageType().(*Message_ExecuteFunctionOnRegionRequest); ok {
		return x.ExecuteFunctionOnRegionRequest
	}
	return nil
}

func (m *Message) GetExecuteFunctionOnRegionResponse() *ExecuteFunctionOnRegionResponse {
	if x, ok := m.GetMessageType().(*Message_ExecuteFunctionOnRegionResponse); ok {
		return x.ExecuteFunctionOnRegionResponse
	}
	return nil
}

func (m *Message) GetAuthenticationRequest() *AuthenticationRequest {
	if x, ok := m.GetMessageType().(*Message_AuthenticationRequest); ok {
		return x.AuthenticationRequest
	}
	return nil
}

func (m *Message) GetAuthenticationResponse() *AuthenticationResponse {
	if x, ok := m.GetMessageType().(*Message_AuthenticationResponse); ok {
		return x.AuthenticationResponse
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Message) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Message_OneofMarshaler, _Message_OneofUnmarshaler, _Message_OneofSizer, []interface{}{
		(*Message_ErrorResponse)(nil),
		(*Message_PutRequest)(nil),
		(*Message_PutResponse)(nil),
		(*Message_GetRequest)(nil),
		(*Message_GetResponse)(nil),
		(*Message_PutAllRequest)(nil),
		(*Message_PutAllResponse)(nil),
		(*Message_GetAllRequest)(nil),
		(*Message_GetAllResponse)(nil),
		(*Message_RemoveRequest)(nil),
		(*Message_RemoveResponse)(nil),
		(*Message_GetServerRequest)(nil),
		(*Message_GetServerResponse)(nil),
		(*Message_GetRegionNamesRequest)(nil),
		(*Message_GetRegionNamesResponse)(nil),
		(*Message_GetRegionRequest)(nil),
		(*Message_GetRegionResponse)(nil),
		(*Message_ExecuteFunctionOnRegionRequest)(nil),
		(*Message_ExecuteFunctionOnRegionResponse)(nil),
		(*Message_AuthenticationRequest)(nil),
		(*Message_AuthenticationResponse)(nil),
	}
}

func _Message_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Message)
	// messageType
	switch x := m.MessageType.(type) {
	case *Message_ErrorResponse:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ErrorResponse); err != nil {
			return err
		}
	case *Message_PutRequest:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PutRequest); err != nil {
			return err
		}
	case *Message_PutResponse:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PutResponse); err != nil {
			return err
		}
	case *Message_GetRequest:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GetRequest); err != nil {
			return err
		}
	case *Message_GetResponse:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GetResponse); err != nil {
			return err
		}
	case *Message_PutAllRequest:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PutAllRequest); err != nil {
			return err
		}
	case *Message_PutAllResponse:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PutAllResponse); err != nil {
			return err
		}
	case *Message_GetAllRequest:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GetAllRequest); err != nil {
			return err
		}
	case *Message_GetAllResponse:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GetAllResponse); err != nil {
			return err
		}
	case *Message_RemoveRequest:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RemoveRequest); err != nil {
			return err
		}
	case *Message_RemoveResponse:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RemoveResponse); err != nil {
			return err
		}
	case *Message_GetServerRequest:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GetServerRequest); err != nil {
			return err
		}
	case *Message_GetServerResponse:
		b.EncodeVarint(13<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GetServerResponse); err != nil {
			return err
		}
	case *Message_GetRegionNamesRequest:
		b.EncodeVarint(14<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GetRegionNamesRequest); err != nil {
			return err
		}
	case *Message_GetRegionNamesResponse:
		b.EncodeVarint(15<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GetRegionNamesResponse); err != nil {
			return err
		}
	case *Message_GetRegionRequest:
		b.EncodeVarint(16<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GetRegionRequest); err != nil {
			return err
		}
	case *Message_GetRegionResponse:
		b.EncodeVarint(17<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GetRegionResponse); err != nil {
			return err
		}
	case *Message_ExecuteFunctionOnRegionRequest:
		b.EncodeVarint(18<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ExecuteFunctionOnRegionRequest); err != nil {
			return err
		}
	case *Message_ExecuteFunctionOnRegionResponse:
		b.EncodeVarint(19<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ExecuteFunctionOnRegionResponse); err != nil {
			return err
		}
	case *Message_AuthenticationRequest:
		b.EncodeVarint(20<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.AuthenticationRequest); err != nil {
			return err
		}
	case *Message_AuthenticationResponse:
		b.EncodeVarint(21<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.AuthenticationResponse); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Message.MessageType has unexpected type %T", x)
	}
	return nil
}

func _Message_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Message)
	switch tag {
	case 1: // messageType.errorResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ErrorResponse)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_ErrorResponse{msg}
		return true, err
	case 2: // messageType.putRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PutRequest)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_PutRequest{msg}
		return true, err
	case 3: // messageType.putResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PutResponse)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_PutResponse{msg}
		return true, err
	case 4: // messageType.getRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetRequest)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_GetRequest{msg}
		return true, err
	case 5: // messageType.getResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetResponse)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_GetResponse{msg}
		return true, err
	case 6: // messageType.putAllRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PutAllRequest)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_PutAllRequest{msg}
		return true, err
	case 7: // messageType.putAllResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PutAllResponse)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_PutAllResponse{msg}
		return true, err
	case 8: // messageType.getAllRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetAllRequest)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_GetAllRequest{msg}
		return true, err
	case 9: // messageType.getAllResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetAllResponse)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_GetAllResponse{msg}
		return true, err
	case 10: // messageType.removeRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RemoveRequest)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_RemoveRequest{msg}
		return true, err
	case 11: // messageType.removeResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RemoveResponse)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_RemoveResponse{msg}
		return true, err
	case 12: // messageType.getServerRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetServerRequest)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_GetServerRequest{msg}
		return true, err
	case 13: // messageType.getServerResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetServerResponse)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_GetServerResponse{msg}
		return true, err
	case 14: // messageType.getRegionNamesRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetRegionNamesRequest)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_GetRegionNamesRequest{msg}
		return true, err
	case 15: // messageType.getRegionNamesResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetRegionNamesResponse)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_GetRegionNamesResponse{msg}
		return true, err
	case 16: // messageType.getRegionRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetRegionRequest)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_GetRegionRequest{msg}
		return true, err
	case 17: // messageType.getRegionResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetRegionResponse)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_GetRegionResponse{msg}
		return true, err
	case 18: // messageType.executeFunctionOnRegionRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ExecuteFunctionOnRegionRequest)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_ExecuteFunctionOnRegionRequest{msg}
		return true, err
	case 19: // messageType.executeFunctionOnRegionResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ExecuteFunctionOnRegionResponse)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_ExecuteFunctionOnRegionResponse{msg}
		return true, err
	case 20: // messageType.authenticationRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(AuthenticationRequest)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_AuthenticationRequest{msg}
		return true, err
	case 21: // messageType.authenticationResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(AuthenticationResponse)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_AuthenticationResponse{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Message_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Message)
	// messageType
	switch x := m.MessageType.(type) {
	case *Message_ErrorResponse:
		s := proto.Size(x.ErrorResponse)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_PutRequest:
		s := proto.Size(x.PutRequest)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_PutResponse:
		s := proto.Size(x.PutResponse)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_GetRequest:
		s := proto.Size(x.GetRequest)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_GetResponse:
		s := proto.Size(x.GetResponse)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_PutAllRequest:
		s := proto.Size(x.PutAllRequest)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_PutAllResponse:
		s := proto.Size(x.PutAllResponse)
		n += proto.SizeVarint(7<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_GetAllRequest:
		s := proto.Size(x.GetAllRequest)
		n += proto.SizeVarint(8<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_GetAllResponse:
		s := proto.Size(x.GetAllResponse)
		n += proto.SizeVarint(9<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_RemoveRequest:
		s := proto.Size(x.RemoveRequest)
		n += proto.SizeVarint(10<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_RemoveResponse:
		s := proto.Size(x.RemoveResponse)
		n += proto.SizeVarint(11<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_GetServerRequest:
		s := proto.Size(x.GetServerRequest)
		n += proto.SizeVarint(12<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_GetServerResponse:
		s := proto.Size(x.GetServerResponse)
		n += proto.SizeVarint(13<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_GetRegionNamesRequest:
		s := proto.Size(x.GetRegionNamesRequest)
		n += proto.SizeVarint(14<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_GetRegionNamesResponse:
		s := proto.Size(x.GetRegionNamesResponse)
		n += proto.SizeVarint(15<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_GetRegionRequest:
		s := proto.Size(x.GetRegionRequest)
		n += proto.SizeVarint(16<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_GetRegionResponse:
		s := proto.Size(x.GetRegionResponse)
		n += proto.SizeVarint(17<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_ExecuteFunctionOnRegionRequest:
		s := proto.Size(x.ExecuteFunctionOnRegionRequest)
		n += proto.SizeVarint(18<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_ExecuteFunctionOnRegionResponse:
		s := proto.Size(x.ExecuteFunctionOnRegionResponse)
		n += proto.SizeVarint(19<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_AuthenticationRequest:
		s := proto.Size(x.AuthenticationRequest)
		n += proto.SizeVarint(20<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_AuthenticationResponse:
		s := proto.Size(x.AuthenticationResponse)
		n += proto.SizeVarint(21<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ErrorResponse struct {
	Error *Error `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
}

func (m *ErrorResponse) Reset()                    { *m = ErrorResponse{} }
func (m *ErrorResponse) String() string            { return proto.CompactTextString(m) }
func (*ErrorResponse) ProtoMessage()               {}
func (*ErrorResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *ErrorResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "org.apache.geode.internal.protocol.protobuf.v1.Message")
	proto.RegisterType((*ErrorResponse)(nil), "org.apache.geode.internal.protocol.protobuf.v1.ErrorResponse")
}

func init() { proto.RegisterFile("v1/clientProtocol.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 618 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x96, 0x41, 0x6f, 0xd3, 0x3c,
	0x18, 0xc7, 0x93, 0xf7, 0x65, 0x1b, 0xb8, 0x74, 0x6c, 0xde, 0x0a, 0xd3, 0x0e, 0x80, 0x76, 0xe2,
	0x94, 0x2a, 0x20, 0x2e, 0x20, 0x10, 0x41, 0xda, 0x1a, 0x84, 0xd8, 0xaa, 0xc0, 0x71, 0xd2, 0x94,
	0x86, 0x67, 0x69, 0xa4, 0xd4, 0xce, 0x1c, 0x27, 0x82, 0x03, 0x12, 0x1f, 0x03, 0x89, 0x8f, 0xc9,
	0x17, 0x40, 0x76, 0x9d, 0x60, 0x67, 0x19, 0x53, 0x3d, 0x6e, 0xeb, 0x63, 0xeb, 0xf7, 0xfc, 0x7f,
	0x7e, 0xe4, 0xc5, 0xe8, 0x41, 0xed, 0x8f, 0x93, 0x3c, 0x03, 0xc2, 0xa7, 0x8c, 0x72, 0x9a, 0xd0,
	0xdc, 0x2b, 0xc4, 0x1f, 0xd8, 0xa3, 0x2c, 0xf5, 0xe2, 0x22, 0x4e, 0xe6, 0xe0, 0xa5, 0x40, 0x3f,
	0x83, 0x97, 0x11, 0x0e, 0x8c, 0xc4, 0x6a, 0x43, 0xbb, 0x73, 0x56, 0x9d, 0x7b, 0xb5, 0xbf, 0xbf,
	0x53, 0xfb, 0x63, 0x06, 0x69, 0x46, 0xc9, 0x59, 0x30, 0x7d, 0xb7, 0x5c, 0xda, 0xdf, 0xad, 0xfd,
	0x71, 0x4e, 0x93, 0x98, 0x53, 0xa6, 0x55, 0xc5, 0xd6, 0x59, 0x5c, 0x66, 0xc9, 0xa7, 0xaf, 0x05,
	0x94, 0xaa, 0x28, 0x83, 0x50, 0x42, 0x20, 0xe1, 0x26, 0x63, 0x54, 0xfb, 0xe3, 0xf3, 0x8a, 0x74,
	0xca, 0x07, 0xbf, 0x30, 0xda, 0xf8, 0x00, 0x65, 0x19, 0xa7, 0x80, 0x01, 0x0d, 0x81, 0x31, 0xca,
	0x22, 0x28, 0x0b, 0x4a, 0x4a, 0xd8, 0x73, 0x1f, 0xbb, 0x4f, 0x06, 0x4f, 0x5f, 0xad, 0xe8, 0xe0,
	0x1d, 0xea, 0x90, 0xd0, 0x89, 0x4c, 0x2a, 0x3e, 0x45, 0xa8, 0xa8, 0x78, 0x04, 0x17, 0x15, 0x94,
	0x7c, 0xef, 0x3f, 0xd9, 0xe3, 0xc5, 0xaa, 0x3d, 0xa6, 0x2d, 0x21, 0x74, 0x22, 0x8d, 0x87, 0xcf,
	0xd0, 0x40, 0xfe, 0x52, 0x0a, 0xff, 0x4b, 0xfc, 0x4b, 0x2b, 0x7c, 0x2b, 0xa0, 0x13, 0x45, 0xfc,
	0x14, 0xda, 0xf8, 0xb7, 0xec, 0xe2, 0x4f, 0x40, 0x8f, 0xff, 0x87, 0x27, 0xe2, 0xcb, 0x5f, 0x2a,
	0xfe, 0x9a, 0x5d, 0xfc, 0x09, 0x18, 0xf1, 0x35, 0xa2, 0x18, 0x72, 0x51, 0xf1, 0x20, 0xcf, 0x1b,
	0x83, 0x75, 0xbb, 0x21, 0x4f, 0x75, 0x88, 0x18, 0xb2, 0x41, 0xc5, 0x73, 0xb4, 0xd9, 0x14, 0x94,
	0xca, 0x86, 0xec, 0xf3, 0xda, 0xb6, 0x4f, 0x6b, 0xd3, 0xe1, 0x0a, 0xa1, 0x14, 0x74, 0xa1, 0xdb,
	0x76, 0x42, 0x13, 0xe8, 0x08, 0x19, 0x54, 0x21, 0xd4, 0x14, 0x94, 0xd0, 0x1d, 0x3b, 0xa1, 0x09,
	0x74, 0x85, 0x4c, 0xae, 0x10, 0x62, 0xb0, 0xa0, 0x35, 0x34, 0x42, 0xc8, 0x4e, 0x28, 0xd2, 0x21,
	0x42, 0xc8, 0xa0, 0x0a, 0xa1, 0xa6, 0xa0, 0x84, 0x06, 0x76, 0x42, 0x91, 0x41, 0x11, 0x42, 0x26,
	0x17, 0x13, 0xb4, 0x95, 0x02, 0xff, 0x08, 0xac, 0x06, 0xd6, 0x38, 0xdd, 0x95, 0xbd, 0xde, 0x58,
	0x1c, 0x9e, 0xc1, 0x09, 0x9d, 0xe8, 0x12, 0x1b, 0x5f, 0xa0, 0x6d, 0xad, 0xa6, 0xe4, 0x86, 0xb2,
	0x61, 0x70, 0x83, 0x86, 0xad, 0xdf, 0x65, 0x3a, 0xfe, 0x86, 0x46, 0xf2, 0x92, 0x89, 0x7f, 0xdc,
	0xc7, 0xf1, 0x02, 0xca, 0xc6, 0x73, 0x53, 0xb6, 0x3d, 0xb4, 0xba, 0xc0, 0x5d, 0x58, 0xe8, 0x44,
	0xfd, 0x5d, 0xf0, 0x77, 0x17, 0xdd, 0xef, 0xae, 0x28, 0xef, 0x7b, 0x32, 0xc0, 0xd1, 0x4d, 0x03,
	0xb4, 0xf2, 0x57, 0xf4, 0x51, 0x43, 0x5e, 0xae, 0x34, 0xf2, 0x5b, 0xd6, 0x43, 0x36, 0x38, 0x6a,
	0xc8, 0x46, 0x4d, 0x0d, 0xb9, 0xa9, 0x29, 0xd9, 0x6d, 0xeb, 0x21, 0x9b, 0x20, 0x35, 0x64, 0xb3,
	0x88, 0x7f, 0xb8, 0xe8, 0x21, 0x7c, 0x81, 0xa4, 0xe2, 0x70, 0xa4, 0xbe, 0xa4, 0x27, 0xc4, 0x34,
	0xc6, 0x32, 0xc0, 0xf1, 0xca, 0x5f, 0xcc, 0xbf, 0x52, 0x43, 0x27, 0xba, 0xa6, 0x2f, 0xfe, 0xe9,
	0xa2, 0x47, 0x57, 0x6e, 0x51, 0x87, 0xb3, 0x23, 0xb3, 0x9d, 0xfc, 0xb3, 0x6c, 0xed, 0x51, 0x5d,
	0xd7, 0x59, 0xdc, 0x8e, 0xb8, 0xe2, 0x73, 0x20, 0x3c, 0x4b, 0x62, 0xae, 0x1d, 0xd7, 0xae, 0xdd,
	0xed, 0x08, 0xfa, 0x60, 0xe2, 0x76, 0xf4, 0x76, 0x91, 0xb7, 0xa3, 0xbb, 0xa2, 0xce, 0x64, 0x64,
	0x77, 0x3b, 0x82, 0x5e, 0x9a, 0xb8, 0x1d, 0xfd, 0x7d, 0xde, 0x0e, 0xd1, 0x60, 0xb1, 0x7c, 0x65,
	0x89, 0xc7, 0xda, 0xc1, 0x29, 0x1a, 0x1a, 0x8f, 0x24, 0xfc, 0x1e, 0xad, 0xc9, 0x47, 0x92, 0x7a,
	0x72, 0x3d, 0xb7, 0x7b, 0x72, 0x2d, 0x19, 0xb3, 0x75, 0xb9, 0xf2, 0xec, 0x77, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xad, 0x7a, 0x65, 0x95, 0x95, 0x0a, 0x00, 0x00,
}
