// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v1/clientProtocol.proto

package org_apache_geode_internal_protocol_protobuf_v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Message struct {
	// Types that are valid to be assigned to MessageType:
	//	*Message_ErrorResponse
	//	*Message_PutRequest
	//	*Message_PutResponse
	//	*Message_GetRequest
	//	*Message_GetResponse
	//	*Message_PutAllRequest
	//	*Message_PutAllResponse
	//	*Message_GetAllRequest
	//	*Message_GetAllResponse
	//	*Message_RemoveRequest
	//	*Message_RemoveResponse
	//	*Message_GetServerRequest
	//	*Message_GetServerResponse
	//	*Message_GetRegionNamesRequest
	//	*Message_GetRegionNamesResponse
	//	*Message_GetSizeRequest
	//	*Message_GetSizeResponse
	//	*Message_ExecuteFunctionOnRegionRequest
	//	*Message_ExecuteFunctionOnRegionResponse
	//	*Message_ExecuteFunctionOnMemberRequest
	//	*Message_ExecuteFunctionOnMemberResponse
	//	*Message_HandshakeRequest
	//	*Message_HandshakeResponse
	//	*Message_ExecuteFunctionOnGroupRequest
	//	*Message_ExecuteFunctionOnGroupResponse
	//	*Message_OqlQueryRequest
	//	*Message_OqlQueryResponse
	//	*Message_KeySetRequest
	//	*Message_KeySetResponse
	//	*Message_DisconnectClientRequest
	//	*Message_DisconnectClientResponse
	//	*Message_ClearRequest
	//	*Message_ClearResponse
	//	*Message_PutIfAbsentRequest
	//	*Message_PutIfAbsentResponse
	MessageType isMessage_MessageType `protobuf_oneof:"messageType"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type isMessage_MessageType interface {
	isMessage_MessageType()
}

type Message_ErrorResponse struct {
	ErrorResponse *ErrorResponse `protobuf:"bytes,1,opt,name=errorResponse,oneof"`
}
type Message_PutRequest struct {
	PutRequest *PutRequest `protobuf:"bytes,2,opt,name=putRequest,oneof"`
}
type Message_PutResponse struct {
	PutResponse *PutResponse `protobuf:"bytes,3,opt,name=putResponse,oneof"`
}
type Message_GetRequest struct {
	GetRequest *GetRequest `protobuf:"bytes,4,opt,name=getRequest,oneof"`
}
type Message_GetResponse struct {
	GetResponse *GetResponse `protobuf:"bytes,5,opt,name=getResponse,oneof"`
}
type Message_PutAllRequest struct {
	PutAllRequest *PutAllRequest `protobuf:"bytes,6,opt,name=putAllRequest,oneof"`
}
type Message_PutAllResponse struct {
	PutAllResponse *PutAllResponse `protobuf:"bytes,7,opt,name=putAllResponse,oneof"`
}
type Message_GetAllRequest struct {
	GetAllRequest *GetAllRequest `protobuf:"bytes,8,opt,name=getAllRequest,oneof"`
}
type Message_GetAllResponse struct {
	GetAllResponse *GetAllResponse `protobuf:"bytes,9,opt,name=getAllResponse,oneof"`
}
type Message_RemoveRequest struct {
	RemoveRequest *RemoveRequest `protobuf:"bytes,10,opt,name=removeRequest,oneof"`
}
type Message_RemoveResponse struct {
	RemoveResponse *RemoveResponse `protobuf:"bytes,11,opt,name=removeResponse,oneof"`
}
type Message_GetServerRequest struct {
	GetServerRequest *GetServerRequest `protobuf:"bytes,12,opt,name=getServerRequest,oneof"`
}
type Message_GetServerResponse struct {
	GetServerResponse *GetServerResponse `protobuf:"bytes,13,opt,name=getServerResponse,oneof"`
}
type Message_GetRegionNamesRequest struct {
	GetRegionNamesRequest *GetRegionNamesRequest `protobuf:"bytes,14,opt,name=getRegionNamesRequest,oneof"`
}
type Message_GetRegionNamesResponse struct {
	GetRegionNamesResponse *GetRegionNamesResponse `protobuf:"bytes,15,opt,name=getRegionNamesResponse,oneof"`
}
type Message_GetSizeRequest struct {
	GetSizeRequest *GetSizeRequest `protobuf:"bytes,16,opt,name=getSizeRequest,oneof"`
}
type Message_GetSizeResponse struct {
	GetSizeResponse *GetSizeResponse `protobuf:"bytes,17,opt,name=getSizeResponse,oneof"`
}
type Message_ExecuteFunctionOnRegionRequest struct {
	ExecuteFunctionOnRegionRequest *ExecuteFunctionOnRegionRequest `protobuf:"bytes,18,opt,name=executeFunctionOnRegionRequest,oneof"`
}
type Message_ExecuteFunctionOnRegionResponse struct {
	ExecuteFunctionOnRegionResponse *ExecuteFunctionOnRegionResponse `protobuf:"bytes,19,opt,name=executeFunctionOnRegionResponse,oneof"`
}
type Message_ExecuteFunctionOnMemberRequest struct {
	ExecuteFunctionOnMemberRequest *ExecuteFunctionOnMemberRequest `protobuf:"bytes,20,opt,name=executeFunctionOnMemberRequest,oneof"`
}
type Message_ExecuteFunctionOnMemberResponse struct {
	ExecuteFunctionOnMemberResponse *ExecuteFunctionOnMemberResponse `protobuf:"bytes,21,opt,name=executeFunctionOnMemberResponse,oneof"`
}
type Message_HandshakeRequest struct {
	HandshakeRequest *HandshakeRequest `protobuf:"bytes,22,opt,name=handshakeRequest,oneof"`
}
type Message_HandshakeResponse struct {
	HandshakeResponse *HandshakeResponse `protobuf:"bytes,23,opt,name=handshakeResponse,oneof"`
}
type Message_ExecuteFunctionOnGroupRequest struct {
	ExecuteFunctionOnGroupRequest *ExecuteFunctionOnGroupRequest `protobuf:"bytes,24,opt,name=executeFunctionOnGroupRequest,oneof"`
}
type Message_ExecuteFunctionOnGroupResponse struct {
	ExecuteFunctionOnGroupResponse *ExecuteFunctionOnGroupResponse `protobuf:"bytes,25,opt,name=executeFunctionOnGroupResponse,oneof"`
}
type Message_OqlQueryRequest struct {
	OqlQueryRequest *OQLQueryRequest `protobuf:"bytes,26,opt,name=oqlQueryRequest,oneof"`
}
type Message_OqlQueryResponse struct {
	OqlQueryResponse *OQLQueryResponse `protobuf:"bytes,27,opt,name=oqlQueryResponse,oneof"`
}
type Message_KeySetRequest struct {
	KeySetRequest *KeySetRequest `protobuf:"bytes,28,opt,name=keySetRequest,oneof"`
}
type Message_KeySetResponse struct {
	KeySetResponse *KeySetResponse `protobuf:"bytes,29,opt,name=keySetResponse,oneof"`
}
type Message_DisconnectClientRequest struct {
	DisconnectClientRequest *DisconnectClientRequest `protobuf:"bytes,30,opt,name=disconnectClientRequest,oneof"`
}
type Message_DisconnectClientResponse struct {
	DisconnectClientResponse *DisconnectClientResponse `protobuf:"bytes,31,opt,name=disconnectClientResponse,oneof"`
}
type Message_ClearRequest struct {
	ClearRequest *ClearRequest `protobuf:"bytes,32,opt,name=clearRequest,oneof"`
}
type Message_ClearResponse struct {
	ClearResponse *ClearResponse `protobuf:"bytes,33,opt,name=clearResponse,oneof"`
}
type Message_PutIfAbsentRequest struct {
	PutIfAbsentRequest *PutIfAbsentRequest `protobuf:"bytes,34,opt,name=putIfAbsentRequest,oneof"`
}
type Message_PutIfAbsentResponse struct {
	PutIfAbsentResponse *PutIfAbsentResponse `protobuf:"bytes,35,opt,name=putIfAbsentResponse,oneof"`
}

func (*Message_ErrorResponse) isMessage_MessageType()                   {}
func (*Message_PutRequest) isMessage_MessageType()                      {}
func (*Message_PutResponse) isMessage_MessageType()                     {}
func (*Message_GetRequest) isMessage_MessageType()                      {}
func (*Message_GetResponse) isMessage_MessageType()                     {}
func (*Message_PutAllRequest) isMessage_MessageType()                   {}
func (*Message_PutAllResponse) isMessage_MessageType()                  {}
func (*Message_GetAllRequest) isMessage_MessageType()                   {}
func (*Message_GetAllResponse) isMessage_MessageType()                  {}
func (*Message_RemoveRequest) isMessage_MessageType()                   {}
func (*Message_RemoveResponse) isMessage_MessageType()                  {}
func (*Message_GetServerRequest) isMessage_MessageType()                {}
func (*Message_GetServerResponse) isMessage_MessageType()               {}
func (*Message_GetRegionNamesRequest) isMessage_MessageType()           {}
func (*Message_GetRegionNamesResponse) isMessage_MessageType()          {}
func (*Message_GetSizeRequest) isMessage_MessageType()                  {}
func (*Message_GetSizeResponse) isMessage_MessageType()                 {}
func (*Message_ExecuteFunctionOnRegionRequest) isMessage_MessageType()  {}
func (*Message_ExecuteFunctionOnRegionResponse) isMessage_MessageType() {}
func (*Message_ExecuteFunctionOnMemberRequest) isMessage_MessageType()  {}
func (*Message_ExecuteFunctionOnMemberResponse) isMessage_MessageType() {}
func (*Message_HandshakeRequest) isMessage_MessageType()                {}
func (*Message_HandshakeResponse) isMessage_MessageType()               {}
func (*Message_ExecuteFunctionOnGroupRequest) isMessage_MessageType()   {}
func (*Message_ExecuteFunctionOnGroupResponse) isMessage_MessageType()  {}
func (*Message_OqlQueryRequest) isMessage_MessageType()                 {}
func (*Message_OqlQueryResponse) isMessage_MessageType()                {}
func (*Message_KeySetRequest) isMessage_MessageType()                   {}
func (*Message_KeySetResponse) isMessage_MessageType()                  {}
func (*Message_DisconnectClientRequest) isMessage_MessageType()         {}
func (*Message_DisconnectClientResponse) isMessage_MessageType()        {}
func (*Message_ClearRequest) isMessage_MessageType()                    {}
func (*Message_ClearResponse) isMessage_MessageType()                   {}
func (*Message_PutIfAbsentRequest) isMessage_MessageType()              {}
func (*Message_PutIfAbsentResponse) isMessage_MessageType()             {}

func (m *Message) GetMessageType() isMessage_MessageType {
	if m != nil {
		return m.MessageType
	}
	return nil
}

func (m *Message) GetErrorResponse() *ErrorResponse {
	if x, ok := m.GetMessageType().(*Message_ErrorResponse); ok {
		return x.ErrorResponse
	}
	return nil
}

func (m *Message) GetPutRequest() *PutRequest {
	if x, ok := m.GetMessageType().(*Message_PutRequest); ok {
		return x.PutRequest
	}
	return nil
}

func (m *Message) GetPutResponse() *PutResponse {
	if x, ok := m.GetMessageType().(*Message_PutResponse); ok {
		return x.PutResponse
	}
	return nil
}

func (m *Message) GetGetRequest() *GetRequest {
	if x, ok := m.GetMessageType().(*Message_GetRequest); ok {
		return x.GetRequest
	}
	return nil
}

func (m *Message) GetGetResponse() *GetResponse {
	if x, ok := m.GetMessageType().(*Message_GetResponse); ok {
		return x.GetResponse
	}
	return nil
}

func (m *Message) GetPutAllRequest() *PutAllRequest {
	if x, ok := m.GetMessageType().(*Message_PutAllRequest); ok {
		return x.PutAllRequest
	}
	return nil
}

func (m *Message) GetPutAllResponse() *PutAllResponse {
	if x, ok := m.GetMessageType().(*Message_PutAllResponse); ok {
		return x.PutAllResponse
	}
	return nil
}

func (m *Message) GetGetAllRequest() *GetAllRequest {
	if x, ok := m.GetMessageType().(*Message_GetAllRequest); ok {
		return x.GetAllRequest
	}
	return nil
}

func (m *Message) GetGetAllResponse() *GetAllResponse {
	if x, ok := m.GetMessageType().(*Message_GetAllResponse); ok {
		return x.GetAllResponse
	}
	return nil
}

func (m *Message) GetRemoveRequest() *RemoveRequest {
	if x, ok := m.GetMessageType().(*Message_RemoveRequest); ok {
		return x.RemoveRequest
	}
	return nil
}

func (m *Message) GetRemoveResponse() *RemoveResponse {
	if x, ok := m.GetMessageType().(*Message_RemoveResponse); ok {
		return x.RemoveResponse
	}
	return nil
}

func (m *Message) GetGetServerRequest() *GetServerRequest {
	if x, ok := m.GetMessageType().(*Message_GetServerRequest); ok {
		return x.GetServerRequest
	}
	return nil
}

func (m *Message) GetGetServerResponse() *GetServerResponse {
	if x, ok := m.GetMessageType().(*Message_GetServerResponse); ok {
		return x.GetServerResponse
	}
	return nil
}

func (m *Message) GetGetRegionNamesRequest() *GetRegionNamesRequest {
	if x, ok := m.GetMessageType().(*Message_GetRegionNamesRequest); ok {
		return x.GetRegionNamesRequest
	}
	return nil
}

func (m *Message) GetGetRegionNamesResponse() *GetRegionNamesResponse {
	if x, ok := m.GetMessageType().(*Message_GetRegionNamesResponse); ok {
		return x.GetRegionNamesResponse
	}
	return nil
}

func (m *Message) GetGetSizeRequest() *GetSizeRequest {
	if x, ok := m.GetMessageType().(*Message_GetSizeRequest); ok {
		return x.GetSizeRequest
	}
	return nil
}

func (m *Message) GetGetSizeResponse() *GetSizeResponse {
	if x, ok := m.GetMessageType().(*Message_GetSizeResponse); ok {
		return x.GetSizeResponse
	}
	return nil
}

func (m *Message) GetExecuteFunctionOnRegionRequest() *ExecuteFunctionOnRegionRequest {
	if x, ok := m.GetMessageType().(*Message_ExecuteFunctionOnRegionRequest); ok {
		return x.ExecuteFunctionOnRegionRequest
	}
	return nil
}

func (m *Message) GetExecuteFunctionOnRegionResponse() *ExecuteFunctionOnRegionResponse {
	if x, ok := m.GetMessageType().(*Message_ExecuteFunctionOnRegionResponse); ok {
		return x.ExecuteFunctionOnRegionResponse
	}
	return nil
}

func (m *Message) GetExecuteFunctionOnMemberRequest() *ExecuteFunctionOnMemberRequest {
	if x, ok := m.GetMessageType().(*Message_ExecuteFunctionOnMemberRequest); ok {
		return x.ExecuteFunctionOnMemberRequest
	}
	return nil
}

func (m *Message) GetExecuteFunctionOnMemberResponse() *ExecuteFunctionOnMemberResponse {
	if x, ok := m.GetMessageType().(*Message_ExecuteFunctionOnMemberResponse); ok {
		return x.ExecuteFunctionOnMemberResponse
	}
	return nil
}

func (m *Message) GetHandshakeRequest() *HandshakeRequest {
	if x, ok := m.GetMessageType().(*Message_HandshakeRequest); ok {
		return x.HandshakeRequest
	}
	return nil
}

func (m *Message) GetHandshakeResponse() *HandshakeResponse {
	if x, ok := m.GetMessageType().(*Message_HandshakeResponse); ok {
		return x.HandshakeResponse
	}
	return nil
}

func (m *Message) GetExecuteFunctionOnGroupRequest() *ExecuteFunctionOnGroupRequest {
	if x, ok := m.GetMessageType().(*Message_ExecuteFunctionOnGroupRequest); ok {
		return x.ExecuteFunctionOnGroupRequest
	}
	return nil
}

func (m *Message) GetExecuteFunctionOnGroupResponse() *ExecuteFunctionOnGroupResponse {
	if x, ok := m.GetMessageType().(*Message_ExecuteFunctionOnGroupResponse); ok {
		return x.ExecuteFunctionOnGroupResponse
	}
	return nil
}

func (m *Message) GetOqlQueryRequest() *OQLQueryRequest {
	if x, ok := m.GetMessageType().(*Message_OqlQueryRequest); ok {
		return x.OqlQueryRequest
	}
	return nil
}

func (m *Message) GetOqlQueryResponse() *OQLQueryResponse {
	if x, ok := m.GetMessageType().(*Message_OqlQueryResponse); ok {
		return x.OqlQueryResponse
	}
	return nil
}

func (m *Message) GetKeySetRequest() *KeySetRequest {
	if x, ok := m.GetMessageType().(*Message_KeySetRequest); ok {
		return x.KeySetRequest
	}
	return nil
}

func (m *Message) GetKeySetResponse() *KeySetResponse {
	if x, ok := m.GetMessageType().(*Message_KeySetResponse); ok {
		return x.KeySetResponse
	}
	return nil
}

func (m *Message) GetDisconnectClientRequest() *DisconnectClientRequest {
	if x, ok := m.GetMessageType().(*Message_DisconnectClientRequest); ok {
		return x.DisconnectClientRequest
	}
	return nil
}

func (m *Message) GetDisconnectClientResponse() *DisconnectClientResponse {
	if x, ok := m.GetMessageType().(*Message_DisconnectClientResponse); ok {
		return x.DisconnectClientResponse
	}
	return nil
}

func (m *Message) GetClearRequest() *ClearRequest {
	if x, ok := m.GetMessageType().(*Message_ClearRequest); ok {
		return x.ClearRequest
	}
	return nil
}

func (m *Message) GetClearResponse() *ClearResponse {
	if x, ok := m.GetMessageType().(*Message_ClearResponse); ok {
		return x.ClearResponse
	}
	return nil
}

func (m *Message) GetPutIfAbsentRequest() *PutIfAbsentRequest {
	if x, ok := m.GetMessageType().(*Message_PutIfAbsentRequest); ok {
		return x.PutIfAbsentRequest
	}
	return nil
}

func (m *Message) GetPutIfAbsentResponse() *PutIfAbsentResponse {
	if x, ok := m.GetMessageType().(*Message_PutIfAbsentResponse); ok {
		return x.PutIfAbsentResponse
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Message) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Message_OneofMarshaler, _Message_OneofUnmarshaler, _Message_OneofSizer, []interface{}{
		(*Message_ErrorResponse)(nil),
		(*Message_PutRequest)(nil),
		(*Message_PutResponse)(nil),
		(*Message_GetRequest)(nil),
		(*Message_GetResponse)(nil),
		(*Message_PutAllRequest)(nil),
		(*Message_PutAllResponse)(nil),
		(*Message_GetAllRequest)(nil),
		(*Message_GetAllResponse)(nil),
		(*Message_RemoveRequest)(nil),
		(*Message_RemoveResponse)(nil),
		(*Message_GetServerRequest)(nil),
		(*Message_GetServerResponse)(nil),
		(*Message_GetRegionNamesRequest)(nil),
		(*Message_GetRegionNamesResponse)(nil),
		(*Message_GetSizeRequest)(nil),
		(*Message_GetSizeResponse)(nil),
		(*Message_ExecuteFunctionOnRegionRequest)(nil),
		(*Message_ExecuteFunctionOnRegionResponse)(nil),
		(*Message_ExecuteFunctionOnMemberRequest)(nil),
		(*Message_ExecuteFunctionOnMemberResponse)(nil),
		(*Message_HandshakeRequest)(nil),
		(*Message_HandshakeResponse)(nil),
		(*Message_ExecuteFunctionOnGroupRequest)(nil),
		(*Message_ExecuteFunctionOnGroupResponse)(nil),
		(*Message_OqlQueryRequest)(nil),
		(*Message_OqlQueryResponse)(nil),
		(*Message_KeySetRequest)(nil),
		(*Message_KeySetResponse)(nil),
		(*Message_DisconnectClientRequest)(nil),
		(*Message_DisconnectClientResponse)(nil),
		(*Message_ClearRequest)(nil),
		(*Message_ClearResponse)(nil),
		(*Message_PutIfAbsentRequest)(nil),
		(*Message_PutIfAbsentResponse)(nil),
	}
}

func _Message_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Message)
	// messageType
	switch x := m.MessageType.(type) {
	case *Message_ErrorResponse:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ErrorResponse); err != nil {
			return err
		}
	case *Message_PutRequest:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PutRequest); err != nil {
			return err
		}
	case *Message_PutResponse:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PutResponse); err != nil {
			return err
		}
	case *Message_GetRequest:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GetRequest); err != nil {
			return err
		}
	case *Message_GetResponse:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GetResponse); err != nil {
			return err
		}
	case *Message_PutAllRequest:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PutAllRequest); err != nil {
			return err
		}
	case *Message_PutAllResponse:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PutAllResponse); err != nil {
			return err
		}
	case *Message_GetAllRequest:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GetAllRequest); err != nil {
			return err
		}
	case *Message_GetAllResponse:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GetAllResponse); err != nil {
			return err
		}
	case *Message_RemoveRequest:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RemoveRequest); err != nil {
			return err
		}
	case *Message_RemoveResponse:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RemoveResponse); err != nil {
			return err
		}
	case *Message_GetServerRequest:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GetServerRequest); err != nil {
			return err
		}
	case *Message_GetServerResponse:
		b.EncodeVarint(13<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GetServerResponse); err != nil {
			return err
		}
	case *Message_GetRegionNamesRequest:
		b.EncodeVarint(14<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GetRegionNamesRequest); err != nil {
			return err
		}
	case *Message_GetRegionNamesResponse:
		b.EncodeVarint(15<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GetRegionNamesResponse); err != nil {
			return err
		}
	case *Message_GetSizeRequest:
		b.EncodeVarint(16<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GetSizeRequest); err != nil {
			return err
		}
	case *Message_GetSizeResponse:
		b.EncodeVarint(17<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GetSizeResponse); err != nil {
			return err
		}
	case *Message_ExecuteFunctionOnRegionRequest:
		b.EncodeVarint(18<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ExecuteFunctionOnRegionRequest); err != nil {
			return err
		}
	case *Message_ExecuteFunctionOnRegionResponse:
		b.EncodeVarint(19<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ExecuteFunctionOnRegionResponse); err != nil {
			return err
		}
	case *Message_ExecuteFunctionOnMemberRequest:
		b.EncodeVarint(20<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ExecuteFunctionOnMemberRequest); err != nil {
			return err
		}
	case *Message_ExecuteFunctionOnMemberResponse:
		b.EncodeVarint(21<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ExecuteFunctionOnMemberResponse); err != nil {
			return err
		}
	case *Message_HandshakeRequest:
		b.EncodeVarint(22<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.HandshakeRequest); err != nil {
			return err
		}
	case *Message_HandshakeResponse:
		b.EncodeVarint(23<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.HandshakeResponse); err != nil {
			return err
		}
	case *Message_ExecuteFunctionOnGroupRequest:
		b.EncodeVarint(24<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ExecuteFunctionOnGroupRequest); err != nil {
			return err
		}
	case *Message_ExecuteFunctionOnGroupResponse:
		b.EncodeVarint(25<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ExecuteFunctionOnGroupResponse); err != nil {
			return err
		}
	case *Message_OqlQueryRequest:
		b.EncodeVarint(26<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.OqlQueryRequest); err != nil {
			return err
		}
	case *Message_OqlQueryResponse:
		b.EncodeVarint(27<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.OqlQueryResponse); err != nil {
			return err
		}
	case *Message_KeySetRequest:
		b.EncodeVarint(28<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.KeySetRequest); err != nil {
			return err
		}
	case *Message_KeySetResponse:
		b.EncodeVarint(29<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.KeySetResponse); err != nil {
			return err
		}
	case *Message_DisconnectClientRequest:
		b.EncodeVarint(30<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DisconnectClientRequest); err != nil {
			return err
		}
	case *Message_DisconnectClientResponse:
		b.EncodeVarint(31<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DisconnectClientResponse); err != nil {
			return err
		}
	case *Message_ClearRequest:
		b.EncodeVarint(32<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ClearRequest); err != nil {
			return err
		}
	case *Message_ClearResponse:
		b.EncodeVarint(33<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ClearResponse); err != nil {
			return err
		}
	case *Message_PutIfAbsentRequest:
		b.EncodeVarint(34<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PutIfAbsentRequest); err != nil {
			return err
		}
	case *Message_PutIfAbsentResponse:
		b.EncodeVarint(35<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PutIfAbsentResponse); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Message.MessageType has unexpected type %T", x)
	}
	return nil
}

func _Message_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Message)
	switch tag {
	case 1: // messageType.errorResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ErrorResponse)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_ErrorResponse{msg}
		return true, err
	case 2: // messageType.putRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PutRequest)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_PutRequest{msg}
		return true, err
	case 3: // messageType.putResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PutResponse)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_PutResponse{msg}
		return true, err
	case 4: // messageType.getRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetRequest)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_GetRequest{msg}
		return true, err
	case 5: // messageType.getResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetResponse)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_GetResponse{msg}
		return true, err
	case 6: // messageType.putAllRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PutAllRequest)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_PutAllRequest{msg}
		return true, err
	case 7: // messageType.putAllResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PutAllResponse)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_PutAllResponse{msg}
		return true, err
	case 8: // messageType.getAllRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetAllRequest)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_GetAllRequest{msg}
		return true, err
	case 9: // messageType.getAllResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetAllResponse)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_GetAllResponse{msg}
		return true, err
	case 10: // messageType.removeRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RemoveRequest)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_RemoveRequest{msg}
		return true, err
	case 11: // messageType.removeResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RemoveResponse)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_RemoveResponse{msg}
		return true, err
	case 12: // messageType.getServerRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetServerRequest)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_GetServerRequest{msg}
		return true, err
	case 13: // messageType.getServerResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetServerResponse)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_GetServerResponse{msg}
		return true, err
	case 14: // messageType.getRegionNamesRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetRegionNamesRequest)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_GetRegionNamesRequest{msg}
		return true, err
	case 15: // messageType.getRegionNamesResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetRegionNamesResponse)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_GetRegionNamesResponse{msg}
		return true, err
	case 16: // messageType.getSizeRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetSizeRequest)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_GetSizeRequest{msg}
		return true, err
	case 17: // messageType.getSizeResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetSizeResponse)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_GetSizeResponse{msg}
		return true, err
	case 18: // messageType.executeFunctionOnRegionRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ExecuteFunctionOnRegionRequest)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_ExecuteFunctionOnRegionRequest{msg}
		return true, err
	case 19: // messageType.executeFunctionOnRegionResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ExecuteFunctionOnRegionResponse)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_ExecuteFunctionOnRegionResponse{msg}
		return true, err
	case 20: // messageType.executeFunctionOnMemberRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ExecuteFunctionOnMemberRequest)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_ExecuteFunctionOnMemberRequest{msg}
		return true, err
	case 21: // messageType.executeFunctionOnMemberResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ExecuteFunctionOnMemberResponse)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_ExecuteFunctionOnMemberResponse{msg}
		return true, err
	case 22: // messageType.handshakeRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(HandshakeRequest)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_HandshakeRequest{msg}
		return true, err
	case 23: // messageType.handshakeResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(HandshakeResponse)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_HandshakeResponse{msg}
		return true, err
	case 24: // messageType.executeFunctionOnGroupRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ExecuteFunctionOnGroupRequest)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_ExecuteFunctionOnGroupRequest{msg}
		return true, err
	case 25: // messageType.executeFunctionOnGroupResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ExecuteFunctionOnGroupResponse)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_ExecuteFunctionOnGroupResponse{msg}
		return true, err
	case 26: // messageType.oqlQueryRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(OQLQueryRequest)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_OqlQueryRequest{msg}
		return true, err
	case 27: // messageType.oqlQueryResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(OQLQueryResponse)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_OqlQueryResponse{msg}
		return true, err
	case 28: // messageType.keySetRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(KeySetRequest)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_KeySetRequest{msg}
		return true, err
	case 29: // messageType.keySetResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(KeySetResponse)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_KeySetResponse{msg}
		return true, err
	case 30: // messageType.disconnectClientRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DisconnectClientRequest)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_DisconnectClientRequest{msg}
		return true, err
	case 31: // messageType.disconnectClientResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DisconnectClientResponse)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_DisconnectClientResponse{msg}
		return true, err
	case 32: // messageType.clearRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ClearRequest)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_ClearRequest{msg}
		return true, err
	case 33: // messageType.clearResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ClearResponse)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_ClearResponse{msg}
		return true, err
	case 34: // messageType.putIfAbsentRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PutIfAbsentRequest)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_PutIfAbsentRequest{msg}
		return true, err
	case 35: // messageType.putIfAbsentResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PutIfAbsentResponse)
		err := b.DecodeMessage(msg)
		m.MessageType = &Message_PutIfAbsentResponse{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Message_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Message)
	// messageType
	switch x := m.MessageType.(type) {
	case *Message_ErrorResponse:
		s := proto.Size(x.ErrorResponse)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_PutRequest:
		s := proto.Size(x.PutRequest)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_PutResponse:
		s := proto.Size(x.PutResponse)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_GetRequest:
		s := proto.Size(x.GetRequest)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_GetResponse:
		s := proto.Size(x.GetResponse)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_PutAllRequest:
		s := proto.Size(x.PutAllRequest)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_PutAllResponse:
		s := proto.Size(x.PutAllResponse)
		n += proto.SizeVarint(7<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_GetAllRequest:
		s := proto.Size(x.GetAllRequest)
		n += proto.SizeVarint(8<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_GetAllResponse:
		s := proto.Size(x.GetAllResponse)
		n += proto.SizeVarint(9<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_RemoveRequest:
		s := proto.Size(x.RemoveRequest)
		n += proto.SizeVarint(10<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_RemoveResponse:
		s := proto.Size(x.RemoveResponse)
		n += proto.SizeVarint(11<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_GetServerRequest:
		s := proto.Size(x.GetServerRequest)
		n += proto.SizeVarint(12<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_GetServerResponse:
		s := proto.Size(x.GetServerResponse)
		n += proto.SizeVarint(13<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_GetRegionNamesRequest:
		s := proto.Size(x.GetRegionNamesRequest)
		n += proto.SizeVarint(14<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_GetRegionNamesResponse:
		s := proto.Size(x.GetRegionNamesResponse)
		n += proto.SizeVarint(15<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_GetSizeRequest:
		s := proto.Size(x.GetSizeRequest)
		n += proto.SizeVarint(16<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_GetSizeResponse:
		s := proto.Size(x.GetSizeResponse)
		n += proto.SizeVarint(17<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_ExecuteFunctionOnRegionRequest:
		s := proto.Size(x.ExecuteFunctionOnRegionRequest)
		n += proto.SizeVarint(18<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_ExecuteFunctionOnRegionResponse:
		s := proto.Size(x.ExecuteFunctionOnRegionResponse)
		n += proto.SizeVarint(19<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_ExecuteFunctionOnMemberRequest:
		s := proto.Size(x.ExecuteFunctionOnMemberRequest)
		n += proto.SizeVarint(20<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_ExecuteFunctionOnMemberResponse:
		s := proto.Size(x.ExecuteFunctionOnMemberResponse)
		n += proto.SizeVarint(21<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_HandshakeRequest:
		s := proto.Size(x.HandshakeRequest)
		n += proto.SizeVarint(22<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_HandshakeResponse:
		s := proto.Size(x.HandshakeResponse)
		n += proto.SizeVarint(23<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_ExecuteFunctionOnGroupRequest:
		s := proto.Size(x.ExecuteFunctionOnGroupRequest)
		n += proto.SizeVarint(24<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_ExecuteFunctionOnGroupResponse:
		s := proto.Size(x.ExecuteFunctionOnGroupResponse)
		n += proto.SizeVarint(25<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_OqlQueryRequest:
		s := proto.Size(x.OqlQueryRequest)
		n += proto.SizeVarint(26<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_OqlQueryResponse:
		s := proto.Size(x.OqlQueryResponse)
		n += proto.SizeVarint(27<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_KeySetRequest:
		s := proto.Size(x.KeySetRequest)
		n += proto.SizeVarint(28<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_KeySetResponse:
		s := proto.Size(x.KeySetResponse)
		n += proto.SizeVarint(29<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_DisconnectClientRequest:
		s := proto.Size(x.DisconnectClientRequest)
		n += proto.SizeVarint(30<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_DisconnectClientResponse:
		s := proto.Size(x.DisconnectClientResponse)
		n += proto.SizeVarint(31<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_ClearRequest:
		s := proto.Size(x.ClearRequest)
		n += proto.SizeVarint(32<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_ClearResponse:
		s := proto.Size(x.ClearResponse)
		n += proto.SizeVarint(33<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_PutIfAbsentRequest:
		s := proto.Size(x.PutIfAbsentRequest)
		n += proto.SizeVarint(34<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_PutIfAbsentResponse:
		s := proto.Size(x.PutIfAbsentResponse)
		n += proto.SizeVarint(35<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ErrorResponse struct {
	Error *Error `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
}

func (m *ErrorResponse) Reset()                    { *m = ErrorResponse{} }
func (m *ErrorResponse) String() string            { return proto.CompactTextString(m) }
func (*ErrorResponse) ProtoMessage()               {}
func (*ErrorResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *ErrorResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "org.apache.geode.internal.protocol.protobuf.v1.Message")
	proto.RegisterType((*ErrorResponse)(nil), "org.apache.geode.internal.protocol.protobuf.v1.ErrorResponse")
}

func init() { proto.RegisterFile("v1/clientProtocol.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 910 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x98, 0x5b, 0x4f, 0xdb, 0x48,
	0x14, 0xc7, 0xed, 0xdd, 0x05, 0x76, 0x27, 0x84, 0xcb, 0x70, 0xcb, 0xd2, 0x72, 0x29, 0x7d, 0xe9,
	0x53, 0xa2, 0xb4, 0xea, 0x4b, 0xef, 0x21, 0x85, 0x18, 0x51, 0x20, 0x18, 0x1e, 0x91, 0x90, 0x63,
	0x0e, 0x49, 0x44, 0x62, 0x1b, 0x5f, 0xd2, 0xa6, 0x52, 0xa5, 0x4a, 0x95, 0xfa, 0x0d, 0x2a, 0x55,
	0xea, 0x47, 0xe8, 0x97, 0xac, 0x66, 0x32, 0x9e, 0xcc, 0x38, 0x0e, 0x28, 0x93, 0xbc, 0x25, 0xc7,
	0xa3, 0xdf, 0xff, 0xfc, 0x8f, 0xcf, 0x1c, 0x7b, 0x8c, 0xd6, 0x3a, 0xc5, 0x82, 0xdd, 0x6a, 0x82,
	0x13, 0x56, 0x7d, 0x37, 0x74, 0x6d, 0xb7, 0x95, 0xf7, 0xc8, 0x0f, 0x9c, 0x77, 0xfd, 0x7a, 0xde,
	0xf2, 0x2c, 0xbb, 0x01, 0xf9, 0x3a, 0xb8, 0x57, 0x90, 0x6f, 0x3a, 0x21, 0xf8, 0x8e, 0xc5, 0x16,
	0xf0, 0x95, 0xb5, 0xe8, 0x3a, 0xdf, 0x29, 0xae, 0x2f, 0x75, 0x8a, 0x05, 0x1f, 0xea, 0x4d, 0xd7,
	0xb9, 0x2c, 0x55, 0x0f, 0x7a, 0x97, 0xd6, 0x97, 0x3b, 0xc5, 0x42, 0xcb, 0xb5, 0xad, 0xd0, 0xf5,
	0x85, 0x28, 0x59, 0x5a, 0xb3, 0x82, 0xa6, 0x7d, 0xde, 0xf5, 0x20, 0x60, 0x41, 0x9a, 0x88, 0xeb,
	0x38, 0x60, 0x87, 0x32, 0x63, 0xa5, 0x53, 0x2c, 0x5c, 0x47, 0x4e, 0x22, 0xbc, 0xf3, 0x7b, 0x1b,
	0xcd, 0x1c, 0x41, 0x10, 0x58, 0x75, 0xc0, 0x80, 0xb2, 0xe0, 0xfb, 0xae, 0x6f, 0x42, 0xe0, 0xb9,
	0x4e, 0x00, 0x39, 0x7d, 0x5b, 0x7f, 0x92, 0x79, 0xfa, 0x7a, 0x44, 0x0f, 0xf9, 0x3d, 0x11, 0x62,
	0x68, 0xa6, 0x4c, 0xc5, 0x17, 0x08, 0x79, 0x51, 0x68, 0xc2, 0x6d, 0x04, 0x41, 0x98, 0xfb, 0x8b,
	0x6a, 0xbc, 0x18, 0x55, 0xa3, 0xca, 0x09, 0x86, 0x66, 0x0a, 0x3c, 0x7c, 0x89, 0x32, 0xf4, 0x1f,
	0xb3, 0xf0, 0x37, 0xc5, 0xbf, 0x54, 0xc2, 0x73, 0x03, 0x22, 0x91, 0xa4, 0x5f, 0x07, 0x9e, 0xfe,
	0x3f, 0x6a, 0xe9, 0x57, 0x40, 0x4c, 0xbf, 0xcf, 0x23, 0xe9, 0xd3, 0x7f, 0x2c, 0xfd, 0x29, 0xb5,
	0xf4, 0x2b, 0x20, 0xa5, 0x2f, 0x10, 0xc9, 0x4d, 0xf6, 0xa2, 0xb0, 0xd4, 0x6a, 0xc5, 0x0e, 0xa6,
	0xd5, 0x6e, 0x72, 0x55, 0x84, 0x90, 0x9b, 0x2c, 0x51, 0x71, 0x03, 0xcd, 0xc5, 0x01, 0x66, 0x65,
	0x86, 0xea, 0xbc, 0x51, 0xd5, 0xe1, 0x6e, 0x12, 0x5c, 0x62, 0xa8, 0x0e, 0xa2, 0xa1, 0x7f, 0xd5,
	0x0c, 0x55, 0x20, 0x61, 0x48, 0xa2, 0x12, 0x43, 0x71, 0x80, 0x19, 0xfa, 0x4f, 0xcd, 0x50, 0x05,
	0x92, 0x86, 0x64, 0x2e, 0x31, 0xe4, 0x43, 0xdb, 0xed, 0x40, 0x6c, 0x08, 0xa9, 0x19, 0x32, 0x45,
	0x08, 0x31, 0x24, 0x51, 0x89, 0xa1, 0x38, 0xc0, 0x0c, 0x65, 0xd4, 0x0c, 0x99, 0x12, 0x85, 0x18,
	0x92, 0xb9, 0xd8, 0x41, 0x0b, 0x75, 0x08, 0xcf, 0xc0, 0xef, 0x80, 0x1f, 0x7b, 0x9a, 0xa5, 0x5a,
	0xef, 0x14, 0x8a, 0x27, 0x71, 0x0c, 0xcd, 0x1c, 0x60, 0xe3, 0x5b, 0xb4, 0x28, 0xc4, 0x98, 0xb9,
	0x2c, 0x15, 0x2c, 0x8d, 0x21, 0xc8, 0xfd, 0x0d, 0xd2, 0xf1, 0x17, 0xb4, 0x42, 0x37, 0x19, 0x19,
	0xdc, 0xc7, 0x56, 0x1b, 0x82, 0xd8, 0xe7, 0x1c, 0x95, 0xdd, 0x53, 0xda, 0xc0, 0x49, 0x98, 0xa1,
	0x99, 0xe9, 0x2a, 0xf8, 0xab, 0x8e, 0x56, 0x93, 0x57, 0x98, 0xef, 0x79, 0x9a, 0xc0, 0xfe, 0xb8,
	0x09, 0x70, 0xf3, 0x43, 0x74, 0xd8, 0xfe, 0x38, 0x6b, 0x7e, 0xe6, 0x6d, 0xbb, 0xa0, 0xbc, 0x3f,
	0x04, 0x0a, 0xdb, 0x1f, 0x42, 0x04, 0xdf, 0xa0, 0x79, 0x1e, 0x61, 0x26, 0x17, 0xa9, 0xd4, 0x5b,
	0x65, 0x29, 0xee, 0x2e, 0x49, 0xc6, 0x3f, 0x75, 0xb4, 0x09, 0x9f, 0xc0, 0x8e, 0x42, 0xd8, 0x67,
	0x4f, 0xcf, 0x13, 0xa7, 0xe7, 0x3f, 0xf6, 0x89, 0xa9, 0xf8, 0xf1, 0xc8, 0x4f, 0xc9, 0x3b, 0xa9,
	0x86, 0x66, 0xde, 0xa3, 0x8b, 0x7f, 0xe9, 0x68, 0x6b, 0xe8, 0x12, 0x56, 0x98, 0x25, 0x9a, 0xdb,
	0xc9, 0xc4, 0x72, 0xe3, 0x85, 0xba, 0x4f, 0x39, 0xbd, 0x70, 0x47, 0xd0, 0xae, 0xf5, 0x67, 0xc0,
	0xf2, 0x84, 0x0a, 0x27, 0x51, 0x53, 0x0b, 0x27, 0xad, 0x48, 0x2f, 0x5c, 0xbc, 0x84, 0x15, 0x6e,
	0x65, 0x42, 0x85, 0x93, 0xb1, 0xa9, 0x85, 0x93, 0x97, 0x90, 0x69, 0xd9, 0xb0, 0x9c, 0xab, 0xa0,
	0x61, 0xdd, 0xf0, 0xad, 0xb4, 0xaa, 0x36, 0x2d, 0x8d, 0x04, 0x87, 0x4c, 0xcb, 0x24, 0x9b, 0x4c,
	0x4b, 0x21, 0xc6, 0xec, 0xaf, 0xa9, 0x4d, 0x4b, 0x23, 0x09, 0x22, 0xd3, 0x72, 0x80, 0x8e, 0x7f,
	0xe8, 0x68, 0x63, 0xa0, 0x0c, 0x15, 0xdf, 0x8d, 0xbc, 0xd8, 0x70, 0x8e, 0xea, 0x1f, 0x8d, 0x5d,
	0x7e, 0x11, 0x6a, 0x68, 0xe6, 0xdd, 0xaa, 0xe9, 0x3d, 0xcb, 0x56, 0xb0, 0xc2, 0xfc, 0x3f, 0xa1,
	0x9e, 0x95, 0xa8, 0xa9, 0x3d, 0x2b, 0xad, 0x20, 0x43, 0xcf, 0xbd, 0x6d, 0x9d, 0x46, 0xe0, 0x77,
	0xe3, 0x1a, 0xad, 0xab, 0x0d, 0xbd, 0x93, 0xd3, 0x0f, 0x22, 0x86, 0x0c, 0xbd, 0x04, 0x99, 0xb4,
	0x60, 0x3f, 0xc4, 0x8c, 0x3f, 0x50, 0x6b, 0xc1, 0xbe, 0x1a, 0xb7, 0x3a, 0xc0, 0x26, 0x6f, 0x3c,
	0x37, 0xd0, 0x3d, 0xeb, 0xbf, 0x55, 0x3f, 0x54, 0x7b, 0xe3, 0x39, 0x14, 0x21, 0xe4, 0x8d, 0x47,
	0xa2, 0x92, 0x47, 0x54, 0x1c, 0x60, 0xa6, 0x36, 0xd4, 0x1e, 0x51, 0x87, 0x12, 0x85, 0x3c, 0xa2,
	0x64, 0x2e, 0xfe, 0xa6, 0xa3, 0xb5, 0xab, 0x66, 0xc0, 0x0e, 0x62, 0x65, 0x7a, 0x30, 0x8c, 0xbd,
	0x6d, 0x52, 0xcd, 0xca, 0xa8, 0x9a, 0xef, 0xd3, 0x71, 0x86, 0x66, 0x0e, 0x53, 0xc2, 0xdf, 0x75,
	0x94, 0x1b, 0xbc, 0xc6, 0xac, 0x6f, 0xd1, 0x34, 0x8c, 0xf1, 0xd3, 0xe0, 0x45, 0x18, 0xaa, 0x85,
	0x6b, 0x68, 0xd6, 0x6e, 0x81, 0xc5, 0x07, 0xff, 0x36, 0xd5, 0x7e, 0x35, 0xaa, 0x76, 0x59, 0x60,
	0x18, 0x9a, 0x29, 0x31, 0x49, 0x0f, 0xb1, 0xff, 0xcc, 0xe0, 0x23, 0xb5, 0x1e, 0x2a, 0x8b, 0x10,
	0xd2, 0x43, 0x12, 0x15, 0x87, 0x08, 0x7b, 0x51, 0x78, 0x70, 0x5d, 0xaa, 0x05, 0xc2, 0x3d, 0xdd,
	0xa1, 0x5a, 0xbb, 0x0a, 0x67, 0x9b, 0x04, 0xc9, 0xd0, 0xcc, 0x14, 0x3e, 0xfe, 0x88, 0x96, 0xa4,
	0x28, 0xb3, 0xf8, 0x98, 0xca, 0x96, 0xc7, 0x92, 0xe5, 0x46, 0xd3, 0x14, 0x76, 0xb3, 0x28, 0xd3,
	0xee, 0x7d, 0x1d, 0x38, 0xef, 0x7a, 0xb0, 0x73, 0x81, 0xb2, 0xd2, 0xe1, 0x1e, 0x1f, 0xa2, 0x29,
	0x7a, 0xb8, 0x67, 0x9f, 0x0a, 0x9e, 0xab, 0x7d, 0x2a, 0xe8, 0x31, 0x6a, 0xd3, 0xf4, 0xca, 0xb3,
	0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x12, 0xb9, 0x1c, 0x58, 0x4d, 0x11, 0x00, 0x00,
}
