// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v1/connection_API.proto

package org_apache_geode_internal_protocol_protobuf_v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type MajorVersions int32

const (
	MajorVersions_INVALID_MAJOR_VERSION MajorVersions = 0
	MajorVersions_CURRENT_MAJOR_VERSION MajorVersions = 1
)

var MajorVersions_name = map[int32]string{
	0: "INVALID_MAJOR_VERSION",
	1: "CURRENT_MAJOR_VERSION",
}
var MajorVersions_value = map[string]int32{
	"INVALID_MAJOR_VERSION": 0,
	"CURRENT_MAJOR_VERSION": 1,
}

func (x MajorVersions) String() string {
	return proto.EnumName(MajorVersions_name, int32(x))
}
func (MajorVersions) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

type MinorVersions int32

const (
	MinorVersions_INVALID_MINOR_VERSION MinorVersions = 0
	MinorVersions_CURRENT_MINOR_VERSION MinorVersions = 1
)

var MinorVersions_name = map[int32]string{
	0: "INVALID_MINOR_VERSION",
	1: "CURRENT_MINOR_VERSION",
}
var MinorVersions_value = map[string]int32{
	"INVALID_MINOR_VERSION": 0,
	"CURRENT_MINOR_VERSION": 1,
}

func (x MinorVersions) String() string {
	return proto.EnumName(MinorVersions_name, int32(x))
}
func (MinorVersions) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

type HandshakeRequest struct {
	MajorVersion int32 `protobuf:"varint,1,opt,name=majorVersion" json:"majorVersion,omitempty"`
	MinorVersion int32 `protobuf:"varint,2,opt,name=minorVersion" json:"minorVersion,omitempty"`
}

func (m *HandshakeRequest) Reset()                    { *m = HandshakeRequest{} }
func (m *HandshakeRequest) String() string            { return proto.CompactTextString(m) }
func (*HandshakeRequest) ProtoMessage()               {}
func (*HandshakeRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *HandshakeRequest) GetMajorVersion() int32 {
	if m != nil {
		return m.MajorVersion
	}
	return 0
}

func (m *HandshakeRequest) GetMinorVersion() int32 {
	if m != nil {
		return m.MinorVersion
	}
	return 0
}

type HandshakeResponse struct {
	ServerMajorVersion int32 `protobuf:"varint,1,opt,name=serverMajorVersion" json:"serverMajorVersion,omitempty"`
	ServerMinorVersion int32 `protobuf:"varint,2,opt,name=serverMinorVersion" json:"serverMinorVersion,omitempty"`
	HandshakePassed    bool  `protobuf:"varint,3,opt,name=handshakePassed" json:"handshakePassed,omitempty"`
}

func (m *HandshakeResponse) Reset()                    { *m = HandshakeResponse{} }
func (m *HandshakeResponse) String() string            { return proto.CompactTextString(m) }
func (*HandshakeResponse) ProtoMessage()               {}
func (*HandshakeResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *HandshakeResponse) GetServerMajorVersion() int32 {
	if m != nil {
		return m.ServerMajorVersion
	}
	return 0
}

func (m *HandshakeResponse) GetServerMinorVersion() int32 {
	if m != nil {
		return m.ServerMinorVersion
	}
	return 0
}

func (m *HandshakeResponse) GetHandshakePassed() bool {
	if m != nil {
		return m.HandshakePassed
	}
	return false
}

type AuthenticationRequest struct {
	Credentials map[string]string `protobuf:"bytes,1,rep,name=credentials" json:"credentials,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *AuthenticationRequest) Reset()                    { *m = AuthenticationRequest{} }
func (m *AuthenticationRequest) String() string            { return proto.CompactTextString(m) }
func (*AuthenticationRequest) ProtoMessage()               {}
func (*AuthenticationRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *AuthenticationRequest) GetCredentials() map[string]string {
	if m != nil {
		return m.Credentials
	}
	return nil
}

type AuthenticationResponse struct {
	Authenticated bool `protobuf:"varint,1,opt,name=authenticated" json:"authenticated,omitempty"`
}

func (m *AuthenticationResponse) Reset()                    { *m = AuthenticationResponse{} }
func (m *AuthenticationResponse) String() string            { return proto.CompactTextString(m) }
func (*AuthenticationResponse) ProtoMessage()               {}
func (*AuthenticationResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *AuthenticationResponse) GetAuthenticated() bool {
	if m != nil {
		return m.Authenticated
	}
	return false
}

func init() {
	proto.RegisterType((*HandshakeRequest)(nil), "org.apache.geode.internal.protocol.protobuf.v1.HandshakeRequest")
	proto.RegisterType((*HandshakeResponse)(nil), "org.apache.geode.internal.protocol.protobuf.v1.HandshakeResponse")
	proto.RegisterType((*AuthenticationRequest)(nil), "org.apache.geode.internal.protocol.protobuf.v1.AuthenticationRequest")
	proto.RegisterType((*AuthenticationResponse)(nil), "org.apache.geode.internal.protocol.protobuf.v1.AuthenticationResponse")
	proto.RegisterEnum("org.apache.geode.internal.protocol.protobuf.v1.MajorVersions", MajorVersions_name, MajorVersions_value)
	proto.RegisterEnum("org.apache.geode.internal.protocol.protobuf.v1.MinorVersions", MinorVersions_name, MinorVersions_value)
}

func init() { proto.RegisterFile("v1/connection_API.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 372 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x41, 0x8f, 0xd2, 0x40,
	0x1c, 0xc5, 0x1d, 0x08, 0x06, 0x06, 0x89, 0x75, 0x22, 0x8a, 0x9e, 0x48, 0xe3, 0xa1, 0xf1, 0x30,
	0x06, 0xbd, 0x18, 0x0f, 0x24, 0x0d, 0x36, 0xb1, 0x46, 0x0a, 0x19, 0xb5, 0x07, 0x2f, 0x64, 0x68,
	0xff, 0xd2, 0x2e, 0xec, 0x0c, 0x3b, 0xd3, 0x36, 0xcb, 0x87, 0xd9, 0x0f, 0xb5, 0xdf, 0x68, 0xd3,
	0x02, 0xa1, 0x2d, 0xec, 0x61, 0x6f, 0xff, 0x79, 0xef, 0xe5, 0xbd, 0xe4, 0x37, 0xf8, 0x6d, 0x36,
	0xfa, 0x14, 0x48, 0x21, 0x20, 0x48, 0x62, 0x29, 0x16, 0xf6, 0xdc, 0xa5, 0x5b, 0x25, 0x13, 0x49,
	0xa8, 0x54, 0x2b, 0xca, 0xb7, 0x3c, 0x88, 0x80, 0xae, 0x40, 0x86, 0x40, 0x63, 0x91, 0x80, 0x12,
	0x7c, 0xb3, 0x0f, 0x04, 0xf2, 0x70, 0x2c, 0xd3, 0xff, 0x34, 0x1b, 0x99, 0xff, 0xb0, 0xf1, 0x83,
	0x8b, 0x50, 0x47, 0x7c, 0x0d, 0x0c, 0x6e, 0x52, 0xd0, 0x09, 0x31, 0xf1, 0x8b, 0x6b, 0x7e, 0x25,
	0x95, 0x0f, 0x4a, 0xc7, 0x52, 0x0c, 0xd0, 0x10, 0x59, 0x2d, 0x56, 0xd1, 0x8a, 0x4c, 0x2c, 0x4e,
	0x99, 0xc6, 0x21, 0x53, 0xd2, 0xcc, 0x3b, 0x84, 0x5f, 0x95, 0xca, 0xf5, 0x56, 0x0a, 0x0d, 0x84,
	0x62, 0xa2, 0x41, 0x65, 0xa0, 0xa6, 0xe7, 0x1b, 0x17, 0x9c, 0x52, 0xfe, 0x7c, 0xef, 0x82, 0x43,
	0x2c, 0xfc, 0x32, 0x3a, 0x8e, 0xce, 0xb9, 0xd6, 0x10, 0x0e, 0x9a, 0x43, 0x64, 0xb5, 0x59, 0x5d,
	0x36, 0xef, 0x11, 0xee, 0xdb, 0x69, 0x12, 0x81, 0x48, 0xe2, 0x80, 0xe7, 0x20, 0x8f, 0x04, 0x6e,
	0x71, 0x37, 0x50, 0x10, 0xe6, 0x06, 0xdf, 0xe8, 0x01, 0x1a, 0x36, 0xad, 0xee, 0x67, 0xff, 0x89,
	0x6c, 0xe9, 0xc5, 0x6e, 0x3a, 0x39, 0x15, 0x3b, 0x22, 0x51, 0x3b, 0x56, 0x9e, 0x7a, 0x3f, 0xc6,
	0x46, 0x3d, 0x40, 0x0c, 0xdc, 0x5c, 0xc3, 0xae, 0x40, 0xd4, 0x61, 0xf9, 0x49, 0x5e, 0xe3, 0x56,
	0xc6, 0x37, 0x29, 0x14, 0x18, 0x3a, 0x6c, 0xff, 0xf8, 0xd6, 0xf8, 0x8a, 0xcc, 0x31, 0x7e, 0x53,
	0x9f, 0x3d, 0x70, 0xff, 0x80, 0x7b, 0xfc, 0xe4, 0x40, 0x58, 0xf4, 0xb5, 0x59, 0x55, 0xfc, 0xe8,
	0xe0, 0x5e, 0x99, 0xbe, 0x26, 0xef, 0x70, 0xdf, 0xf5, 0x7c, 0xfb, 0x97, 0xfb, 0x7d, 0x31, 0xb5,
	0x7f, 0xce, 0xd8, 0xc2, 0x77, 0xd8, 0x6f, 0x77, 0xe6, 0x19, 0xcf, 0x72, 0x6b, 0xf2, 0x97, 0x31,
	0xc7, 0xfb, 0x53, 0xb3, 0x50, 0x51, 0x53, 0xfa, 0x94, 0x6a, 0x8d, 0xeb, 0x3d, 0x5a, 0x53, 0xb1,
	0xd0, 0xf2, 0x79, 0x81, 0xf3, 0xcb, 0x43, 0x00, 0x00, 0x00, 0xff, 0xff, 0x50, 0x59, 0x72, 0x34,
	0xef, 0x02, 0x00, 0x00,
}
