// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v1/function_API.proto

package org_apache_geode_internal_protocol_protobuf_v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ExecuteFunctionOnRegionRequest struct {
	FunctionID string          `protobuf:"bytes,1,opt,name=functionID" json:"functionID,omitempty"`
	Region     string          `protobuf:"bytes,2,opt,name=region" json:"region,omitempty"`
	Arguments  *EncodedValue   `protobuf:"bytes,3,opt,name=arguments" json:"arguments,omitempty"`
	KeyFilter  []*EncodedValue `protobuf:"bytes,4,rep,name=keyFilter" json:"keyFilter,omitempty"`
}

func (m *ExecuteFunctionOnRegionRequest) Reset()                    { *m = ExecuteFunctionOnRegionRequest{} }
func (m *ExecuteFunctionOnRegionRequest) String() string            { return proto.CompactTextString(m) }
func (*ExecuteFunctionOnRegionRequest) ProtoMessage()               {}
func (*ExecuteFunctionOnRegionRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

func (m *ExecuteFunctionOnRegionRequest) GetFunctionID() string {
	if m != nil {
		return m.FunctionID
	}
	return ""
}

func (m *ExecuteFunctionOnRegionRequest) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *ExecuteFunctionOnRegionRequest) GetArguments() *EncodedValue {
	if m != nil {
		return m.Arguments
	}
	return nil
}

func (m *ExecuteFunctionOnRegionRequest) GetKeyFilter() []*EncodedValue {
	if m != nil {
		return m.KeyFilter
	}
	return nil
}

type ExecuteFunctionOnRegionResponse struct {
	Results []*EncodedValue `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
}

func (m *ExecuteFunctionOnRegionResponse) Reset()                    { *m = ExecuteFunctionOnRegionResponse{} }
func (m *ExecuteFunctionOnRegionResponse) String() string            { return proto.CompactTextString(m) }
func (*ExecuteFunctionOnRegionResponse) ProtoMessage()               {}
func (*ExecuteFunctionOnRegionResponse) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{1} }

func (m *ExecuteFunctionOnRegionResponse) GetResults() []*EncodedValue {
	if m != nil {
		return m.Results
	}
	return nil
}

type ExecuteFunctionOnMemberRequest struct {
	FunctionID string        `protobuf:"bytes,1,opt,name=functionID" json:"functionID,omitempty"`
	MemberName []string      `protobuf:"bytes,2,rep,name=memberName" json:"memberName,omitempty"`
	Arguments  *EncodedValue `protobuf:"bytes,3,opt,name=arguments" json:"arguments,omitempty"`
}

func (m *ExecuteFunctionOnMemberRequest) Reset()                    { *m = ExecuteFunctionOnMemberRequest{} }
func (m *ExecuteFunctionOnMemberRequest) String() string            { return proto.CompactTextString(m) }
func (*ExecuteFunctionOnMemberRequest) ProtoMessage()               {}
func (*ExecuteFunctionOnMemberRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{2} }

func (m *ExecuteFunctionOnMemberRequest) GetFunctionID() string {
	if m != nil {
		return m.FunctionID
	}
	return ""
}

func (m *ExecuteFunctionOnMemberRequest) GetMemberName() []string {
	if m != nil {
		return m.MemberName
	}
	return nil
}

func (m *ExecuteFunctionOnMemberRequest) GetArguments() *EncodedValue {
	if m != nil {
		return m.Arguments
	}
	return nil
}

type ExecuteFunctionOnMemberResponse struct {
	Results []*EncodedValue `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
}

func (m *ExecuteFunctionOnMemberResponse) Reset()                    { *m = ExecuteFunctionOnMemberResponse{} }
func (m *ExecuteFunctionOnMemberResponse) String() string            { return proto.CompactTextString(m) }
func (*ExecuteFunctionOnMemberResponse) ProtoMessage()               {}
func (*ExecuteFunctionOnMemberResponse) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{3} }

func (m *ExecuteFunctionOnMemberResponse) GetResults() []*EncodedValue {
	if m != nil {
		return m.Results
	}
	return nil
}

type ExecuteFunctionOnGroupRequest struct {
	FunctionID string        `protobuf:"bytes,1,opt,name=functionID" json:"functionID,omitempty"`
	GroupName  []string      `protobuf:"bytes,2,rep,name=groupName" json:"groupName,omitempty"`
	Arguments  *EncodedValue `protobuf:"bytes,3,opt,name=arguments" json:"arguments,omitempty"`
}

func (m *ExecuteFunctionOnGroupRequest) Reset()                    { *m = ExecuteFunctionOnGroupRequest{} }
func (m *ExecuteFunctionOnGroupRequest) String() string            { return proto.CompactTextString(m) }
func (*ExecuteFunctionOnGroupRequest) ProtoMessage()               {}
func (*ExecuteFunctionOnGroupRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{4} }

func (m *ExecuteFunctionOnGroupRequest) GetFunctionID() string {
	if m != nil {
		return m.FunctionID
	}
	return ""
}

func (m *ExecuteFunctionOnGroupRequest) GetGroupName() []string {
	if m != nil {
		return m.GroupName
	}
	return nil
}

func (m *ExecuteFunctionOnGroupRequest) GetArguments() *EncodedValue {
	if m != nil {
		return m.Arguments
	}
	return nil
}

type ExecuteFunctionOnGroupResponse struct {
	Results []*EncodedValue `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
}

func (m *ExecuteFunctionOnGroupResponse) Reset()                    { *m = ExecuteFunctionOnGroupResponse{} }
func (m *ExecuteFunctionOnGroupResponse) String() string            { return proto.CompactTextString(m) }
func (*ExecuteFunctionOnGroupResponse) ProtoMessage()               {}
func (*ExecuteFunctionOnGroupResponse) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{5} }

func (m *ExecuteFunctionOnGroupResponse) GetResults() []*EncodedValue {
	if m != nil {
		return m.Results
	}
	return nil
}

func init() {
	proto.RegisterType((*ExecuteFunctionOnRegionRequest)(nil), "org.apache.geode.internal.protocol.protobuf.v1.ExecuteFunctionOnRegionRequest")
	proto.RegisterType((*ExecuteFunctionOnRegionResponse)(nil), "org.apache.geode.internal.protocol.protobuf.v1.ExecuteFunctionOnRegionResponse")
	proto.RegisterType((*ExecuteFunctionOnMemberRequest)(nil), "org.apache.geode.internal.protocol.protobuf.v1.ExecuteFunctionOnMemberRequest")
	proto.RegisterType((*ExecuteFunctionOnMemberResponse)(nil), "org.apache.geode.internal.protocol.protobuf.v1.ExecuteFunctionOnMemberResponse")
	proto.RegisterType((*ExecuteFunctionOnGroupRequest)(nil), "org.apache.geode.internal.protocol.protobuf.v1.ExecuteFunctionOnGroupRequest")
	proto.RegisterType((*ExecuteFunctionOnGroupResponse)(nil), "org.apache.geode.internal.protocol.protobuf.v1.ExecuteFunctionOnGroupResponse")
}

func init() { proto.RegisterFile("v1/function_API.proto", fileDescriptor5) }

var fileDescriptor5 = []byte{
	// 327 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x91, 0xcb, 0x4a, 0xc3, 0x40,
	0x14, 0x86, 0x99, 0x56, 0x2a, 0x3d, 0xee, 0x22, 0xca, 0x20, 0x5a, 0x43, 0x57, 0x5d, 0x4d, 0xa9,
	0x6e, 0xdd, 0x08, 0xb6, 0xd2, 0x85, 0x17, 0x82, 0x74, 0xe1, 0x46, 0x26, 0xd3, 0xd3, 0x18, 0x4c,
	0x66, 0xe2, 0x5c, 0x4a, 0xfb, 0x16, 0xbe, 0x8e, 0xe0, 0xc3, 0x49, 0xd3, 0xd4, 0x16, 0x8c, 0x50,
	0xd1, 0xec, 0x66, 0xce, 0xe5, 0xff, 0x0f, 0xdf, 0x0f, 0x07, 0xd3, 0x5e, 0x77, 0xe2, 0xa4, 0xb0,
	0xb1, 0x92, 0x4f, 0x97, 0xf7, 0x43, 0x96, 0x69, 0x65, 0x95, 0xc7, 0x94, 0x8e, 0x18, 0xcf, 0xb8,
	0x78, 0x46, 0x16, 0xa1, 0x1a, 0x23, 0x8b, 0xa5, 0x45, 0x2d, 0x79, 0xb2, 0x1c, 0x10, 0xaa, 0x78,
	0x84, 0x6e, 0xc2, 0xa6, 0xbd, 0xa3, 0xfd, 0x69, 0xaf, 0x1b, 0x72, 0x13, 0x8b, 0x87, 0x79, 0x86,
	0x66, 0xd9, 0x6a, 0xbf, 0xd5, 0xa0, 0xd5, 0x9f, 0xa1, 0x70, 0x16, 0x07, 0x85, 0xc5, 0x9d, 0x0c,
	0x30, 0x8a, 0x95, 0x0c, 0xf0, 0xd5, 0xa1, 0xb1, 0x5e, 0x0b, 0x60, 0xe5, 0x3e, 0xbc, 0xa2, 0xc4,
	0x27, 0x9d, 0x66, 0xb0, 0x51, 0xf1, 0x0e, 0xa1, 0xa1, 0xf3, 0x05, 0x5a, 0xcb, 0x7b, 0xc5, 0xcf,
	0x7b, 0x84, 0x26, 0xd7, 0x91, 0x4b, 0x51, 0x5a, 0x43, 0xeb, 0x3e, 0xe9, 0xec, 0x9d, 0x5d, 0xfc,
	0xf2, 0x66, 0xd6, 0x97, 0x42, 0x8d, 0x71, 0x3c, 0xe2, 0x89, 0xc3, 0x60, 0x2d, 0xb7, 0xd0, 0x7e,
	0xc1, 0xf9, 0x20, 0x4e, 0x2c, 0x6a, 0xba, 0xe3, 0xd7, 0xff, 0xae, 0xfd, 0x25, 0xd7, 0x9e, 0xc3,
	0xe9, 0x8f, 0x44, 0x4c, 0xa6, 0xa4, 0x41, 0x6f, 0x04, 0xbb, 0x1a, 0x8d, 0x4b, 0xac, 0xa1, 0xe4,
	0x1f, 0xcc, 0x57, 0x62, 0xed, 0x0f, 0x52, 0x92, 0xc6, 0x0d, 0xa6, 0x21, 0xea, 0x6d, 0xd3, 0x68,
	0x01, 0xa4, 0xf9, 0xc2, 0x2d, 0x4f, 0x91, 0xd6, 0xfc, 0xfa, 0xa2, 0xbf, 0xae, 0x54, 0x99, 0x4a,
	0x29, 0xb9, 0xd5, 0xf5, 0x15, 0x93, 0x7b, 0x27, 0x70, 0xf2, 0xcd, 0xfb, 0x5a, 0x2b, 0x97, 0x6d,
	0x0b, 0xee, 0x18, 0x9a, 0xd1, 0x62, 0x7e, 0x83, 0xdb, 0xba, 0x50, 0x29, 0xb6, 0x59, 0x49, 0xe8,
	0xc5, 0xe9, 0xd5, 0x52, 0x0b, 0x1b, 0xf9, 0xc8, 0xf9, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x34,
	0xf2, 0xcd, 0x89, 0x62, 0x04, 0x00, 0x00,
}
