// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v1/region_API.proto

package org_apache_geode_internal_protocol_protobuf_v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type PutRequest struct {
	RegionName string `protobuf:"bytes,1,opt,name=regionName" json:"regionName,omitempty"`
	Entry      *Entry `protobuf:"bytes,2,opt,name=entry" json:"entry,omitempty"`
}

func (m *PutRequest) Reset()                    { *m = PutRequest{} }
func (m *PutRequest) String() string            { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()               {}
func (*PutRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *PutRequest) GetRegionName() string {
	if m != nil {
		return m.RegionName
	}
	return ""
}

func (m *PutRequest) GetEntry() *Entry {
	if m != nil {
		return m.Entry
	}
	return nil
}

type PutResponse struct {
}

func (m *PutResponse) Reset()                    { *m = PutResponse{} }
func (m *PutResponse) String() string            { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()               {}
func (*PutResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

type GetRequest struct {
	RegionName string        `protobuf:"bytes,1,opt,name=regionName" json:"regionName,omitempty"`
	Key        *EncodedValue `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{2} }

func (m *GetRequest) GetRegionName() string {
	if m != nil {
		return m.RegionName
	}
	return ""
}

func (m *GetRequest) GetKey() *EncodedValue {
	if m != nil {
		return m.Key
	}
	return nil
}

type GetResponse struct {
	Result *EncodedValue `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *GetResponse) Reset()                    { *m = GetResponse{} }
func (m *GetResponse) String() string            { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()               {}
func (*GetResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{3} }

func (m *GetResponse) GetResult() *EncodedValue {
	if m != nil {
		return m.Result
	}
	return nil
}

type PutAllRequest struct {
	RegionName string   `protobuf:"bytes,1,opt,name=regionName" json:"regionName,omitempty"`
	Entry      []*Entry `protobuf:"bytes,2,rep,name=entry" json:"entry,omitempty"`
}

func (m *PutAllRequest) Reset()                    { *m = PutAllRequest{} }
func (m *PutAllRequest) String() string            { return proto.CompactTextString(m) }
func (*PutAllRequest) ProtoMessage()               {}
func (*PutAllRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{4} }

func (m *PutAllRequest) GetRegionName() string {
	if m != nil {
		return m.RegionName
	}
	return ""
}

func (m *PutAllRequest) GetEntry() []*Entry {
	if m != nil {
		return m.Entry
	}
	return nil
}

type PutAllResponse struct {
	FailedKeys []*KeyedError `protobuf:"bytes,1,rep,name=failedKeys" json:"failedKeys,omitempty"`
}

func (m *PutAllResponse) Reset()                    { *m = PutAllResponse{} }
func (m *PutAllResponse) String() string            { return proto.CompactTextString(m) }
func (*PutAllResponse) ProtoMessage()               {}
func (*PutAllResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{5} }

func (m *PutAllResponse) GetFailedKeys() []*KeyedError {
	if m != nil {
		return m.FailedKeys
	}
	return nil
}

type GetAllRequest struct {
	RegionName  string          `protobuf:"bytes,1,opt,name=regionName" json:"regionName,omitempty"`
	Key         []*EncodedValue `protobuf:"bytes,2,rep,name=key" json:"key,omitempty"`
	CallbackArg *EncodedValue   `protobuf:"bytes,3,opt,name=callbackArg" json:"callbackArg,omitempty"`
}

func (m *GetAllRequest) Reset()                    { *m = GetAllRequest{} }
func (m *GetAllRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAllRequest) ProtoMessage()               {}
func (*GetAllRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{6} }

func (m *GetAllRequest) GetRegionName() string {
	if m != nil {
		return m.RegionName
	}
	return ""
}

func (m *GetAllRequest) GetKey() []*EncodedValue {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *GetAllRequest) GetCallbackArg() *EncodedValue {
	if m != nil {
		return m.CallbackArg
	}
	return nil
}

type GetAllResponse struct {
	Entries  []*Entry      `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
	Failures []*KeyedError `protobuf:"bytes,2,rep,name=failures" json:"failures,omitempty"`
}

func (m *GetAllResponse) Reset()                    { *m = GetAllResponse{} }
func (m *GetAllResponse) String() string            { return proto.CompactTextString(m) }
func (*GetAllResponse) ProtoMessage()               {}
func (*GetAllResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{7} }

func (m *GetAllResponse) GetEntries() []*Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *GetAllResponse) GetFailures() []*KeyedError {
	if m != nil {
		return m.Failures
	}
	return nil
}

type RemoveRequest struct {
	RegionName string        `protobuf:"bytes,1,opt,name=regionName" json:"regionName,omitempty"`
	Key        *EncodedValue `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
}

func (m *RemoveRequest) Reset()                    { *m = RemoveRequest{} }
func (m *RemoveRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveRequest) ProtoMessage()               {}
func (*RemoveRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{8} }

func (m *RemoveRequest) GetRegionName() string {
	if m != nil {
		return m.RegionName
	}
	return ""
}

func (m *RemoveRequest) GetKey() *EncodedValue {
	if m != nil {
		return m.Key
	}
	return nil
}

type RemoveResponse struct {
}

func (m *RemoveResponse) Reset()                    { *m = RemoveResponse{} }
func (m *RemoveResponse) String() string            { return proto.CompactTextString(m) }
func (*RemoveResponse) ProtoMessage()               {}
func (*RemoveResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{9} }

type GetRegionNamesRequest struct {
}

func (m *GetRegionNamesRequest) Reset()                    { *m = GetRegionNamesRequest{} }
func (m *GetRegionNamesRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRegionNamesRequest) ProtoMessage()               {}
func (*GetRegionNamesRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{10} }

type GetRegionNamesResponse struct {
	Regions []string `protobuf:"bytes,1,rep,name=regions" json:"regions,omitempty"`
}

func (m *GetRegionNamesResponse) Reset()                    { *m = GetRegionNamesResponse{} }
func (m *GetRegionNamesResponse) String() string            { return proto.CompactTextString(m) }
func (*GetRegionNamesResponse) ProtoMessage()               {}
func (*GetRegionNamesResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{11} }

func (m *GetRegionNamesResponse) GetRegions() []string {
	if m != nil {
		return m.Regions
	}
	return nil
}

type GetRegionRequest struct {
	RegionName string `protobuf:"bytes,1,opt,name=regionName" json:"regionName,omitempty"`
}

func (m *GetRegionRequest) Reset()                    { *m = GetRegionRequest{} }
func (m *GetRegionRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRegionRequest) ProtoMessage()               {}
func (*GetRegionRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{12} }

func (m *GetRegionRequest) GetRegionName() string {
	if m != nil {
		return m.RegionName
	}
	return ""
}

type GetRegionResponse struct {
	Region *Region `protobuf:"bytes,1,opt,name=region" json:"region,omitempty"`
}

func (m *GetRegionResponse) Reset()                    { *m = GetRegionResponse{} }
func (m *GetRegionResponse) String() string            { return proto.CompactTextString(m) }
func (*GetRegionResponse) ProtoMessage()               {}
func (*GetRegionResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{13} }

func (m *GetRegionResponse) GetRegion() *Region {
	if m != nil {
		return m.Region
	}
	return nil
}

func init() {
	proto.RegisterType((*PutRequest)(nil), "org.apache.geode.internal.protocol.protobuf.v1.PutRequest")
	proto.RegisterType((*PutResponse)(nil), "org.apache.geode.internal.protocol.protobuf.v1.PutResponse")
	proto.RegisterType((*GetRequest)(nil), "org.apache.geode.internal.protocol.protobuf.v1.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "org.apache.geode.internal.protocol.protobuf.v1.GetResponse")
	proto.RegisterType((*PutAllRequest)(nil), "org.apache.geode.internal.protocol.protobuf.v1.PutAllRequest")
	proto.RegisterType((*PutAllResponse)(nil), "org.apache.geode.internal.protocol.protobuf.v1.PutAllResponse")
	proto.RegisterType((*GetAllRequest)(nil), "org.apache.geode.internal.protocol.protobuf.v1.GetAllRequest")
	proto.RegisterType((*GetAllResponse)(nil), "org.apache.geode.internal.protocol.protobuf.v1.GetAllResponse")
	proto.RegisterType((*RemoveRequest)(nil), "org.apache.geode.internal.protocol.protobuf.v1.RemoveRequest")
	proto.RegisterType((*RemoveResponse)(nil), "org.apache.geode.internal.protocol.protobuf.v1.RemoveResponse")
	proto.RegisterType((*GetRegionNamesRequest)(nil), "org.apache.geode.internal.protocol.protobuf.v1.GetRegionNamesRequest")
	proto.RegisterType((*GetRegionNamesResponse)(nil), "org.apache.geode.internal.protocol.protobuf.v1.GetRegionNamesResponse")
	proto.RegisterType((*GetRegionRequest)(nil), "org.apache.geode.internal.protocol.protobuf.v1.GetRegionRequest")
	proto.RegisterType((*GetRegionResponse)(nil), "org.apache.geode.internal.protocol.protobuf.v1.GetRegionResponse")
}

func init() { proto.RegisterFile("v1/region_API.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 429 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x54, 0xc1, 0xaa, 0xd3, 0x40,
	0x14, 0x25, 0x06, 0xdf, 0xf3, 0xdd, 0x90, 0xf2, 0x8c, 0xa8, 0xc1, 0x85, 0x3c, 0x66, 0xd5, 0x55,
	0xa4, 0x15, 0x5d, 0x88, 0x9b, 0x2e, 0x4a, 0x91, 0x42, 0x2d, 0xa1, 0x74, 0xe1, 0x42, 0x99, 0x4c,
	0x6e, 0x63, 0xe8, 0x34, 0x13, 0x67, 0x92, 0x42, 0xa0, 0xe0, 0x77, 0xf9, 0x35, 0xfe, 0x8a, 0x24,
	0x99, 0x29, 0xc1, 0x55, 0xd3, 0x16, 0xde, 0x2e, 0x99, 0x3b, 0xf7, 0x9c, 0x73, 0xcf, 0xe1, 0x0e,
	0xbc, 0xd8, 0x8f, 0xde, 0x49, 0x4c, 0x52, 0x91, 0xfd, 0x98, 0x2c, 0xbf, 0x04, 0xb9, 0x14, 0x85,
	0xf0, 0x02, 0x21, 0x93, 0x80, 0xe6, 0x94, 0xfd, 0xc4, 0x20, 0x41, 0x11, 0x63, 0x90, 0x66, 0x05,
	0xca, 0x8c, 0xf2, 0xf6, 0x02, 0x13, 0xfa, 0x23, 0x2a, 0x37, 0xc1, 0x7e, 0xf4, 0xa6, 0x06, 0x89,
	0xa8, 0x4a, 0xd9, 0xaa, 0xca, 0x51, 0xb5, 0x25, 0x52, 0x01, 0x2c, 0xcb, 0x22, 0xc4, 0x5f, 0x25,
	0xaa, 0xc2, 0x7b, 0x0b, 0xd0, 0xd2, 0x2c, 0xe8, 0x0e, 0x7d, 0xeb, 0xc1, 0x1a, 0xde, 0x85, 0x9d,
	0x13, 0x6f, 0x0e, 0x4f, 0x31, 0x2b, 0x64, 0xe5, 0x3f, 0x79, 0xb0, 0x86, 0xce, 0xf8, 0x43, 0x4f,
	0x09, 0xc1, 0xb4, 0x6e, 0x0e, 0x5b, 0x0c, 0xe2, 0x82, 0xd3, 0x50, 0xab, 0x5c, 0x64, 0x0a, 0xc9,
	0x01, 0x60, 0x86, 0x27, 0x2b, 0x59, 0x80, 0xbd, 0x45, 0xa3, 0xe3, 0x73, 0x7f, 0x1d, 0x4c, 0xc4,
	0x18, 0xaf, 0x29, 0x2f, 0x31, 0xac, 0x81, 0x08, 0x03, 0xa7, 0x61, 0x6f, 0xc5, 0x78, 0x2b, 0xb8,
	0x91, 0xa8, 0x4a, 0x5e, 0x34, 0xd4, 0x97, 0x32, 0x68, 0x2c, 0x72, 0x00, 0x77, 0x59, 0x16, 0x13,
	0xce, 0xcf, 0xf0, 0xdb, 0xbe, 0xd8, 0x6f, 0x0e, 0x03, 0xc3, 0xae, 0xa7, 0xfc, 0x06, 0xb0, 0xa1,
	0x29, 0xc7, 0x78, 0x8e, 0x95, 0xf2, 0xad, 0x86, 0xe3, 0x53, 0x5f, 0x8e, 0x39, 0x56, 0x18, 0x4f,
	0xa5, 0x14, 0x32, 0xec, 0xa0, 0x91, 0xbf, 0x16, 0xb8, 0x33, 0xec, 0x33, 0xec, 0x31, 0x52, 0xfb,
	0x2a, 0x91, 0x7a, 0xdf, 0xc1, 0x61, 0x94, 0xf3, 0x88, 0xb2, 0xed, 0x44, 0x26, 0xbe, 0x7d, 0x85,
	0x20, 0xbb, 0x80, 0xe4, 0x8f, 0x05, 0x03, 0x33, 0xa1, 0x36, 0xf4, 0x2b, 0xdc, 0xd6, 0x5e, 0xa7,
	0x68, 0xdc, 0x3c, 0x33, 0x31, 0x83, 0xe2, 0xad, 0xe1, 0x59, 0xed, 0x69, 0x29, 0x51, 0x69, 0x63,
	0x2e, 0xc9, 0xe7, 0x88, 0x45, 0x7e, 0x83, 0x1b, 0xe2, 0x4e, 0xec, 0xf1, 0xb1, 0xf6, 0xed, 0x1e,
	0x06, 0x46, 0x80, 0xde, 0xff, 0xd7, 0xf0, 0xb2, 0xd9, 0x40, 0x43, 0xa9, 0xb4, 0x34, 0x32, 0x86,
	0x57, 0xff, 0x17, 0xb4, 0xdd, 0x3e, 0xdc, 0xb6, 0x12, 0x5b, 0xbb, 0xef, 0x42, 0xf3, 0x4b, 0xc6,
	0x70, 0x7f, 0xec, 0x39, 0x71, 0x44, 0xc2, 0xe0, 0x79, 0xa7, 0x47, 0x53, 0x2c, 0xea, 0x87, 0xa0,
	0x3e, 0xd1, 0x0f, 0xc1, 0xc7, 0xbe, 0xa3, 0x6b, 0x3c, 0x8d, 0x12, 0xdd, 0x34, 0xb5, 0xf7, 0xff,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xdf, 0x6d, 0x19, 0x88, 0xd2, 0x05, 0x00, 0x00,
}
